### ISSUE TITLE
Is it possible to know reason when connection to server is failed?

### ISSUE THREAD

**Issue by codegame6** [aws/aws-iot-device-sdk-java-v2#105]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Android

**Describe the question**
I am using java-v2 SDK for Android.
To establish an MQTT connection I am using the connect API of MqttClientConnection.
When the connection fails, it provides ExecutionException but is there any way by which we can know the error number or some other detail by which we can know the cause of connection error like not able to connect to the server, certificate error or any other error. So, it can be used to take appropriate action like try to recover error if possible or show user appropriate error on UI.

I have opened below issue but was not able to provide the requested detail in time and it is closed so I am creating new one.
https://github.com/aws/aws-iot-device-sdk-java-v2/issues/99

Below are some logs for different conditions.
1.  When Internet is not available
W/System.err: java.util.concurrent.ExecutionException: software.amazon.awssdk.crt.mqtt.MqttException: System call failure
W/System.err:     at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:359)
W/System.err:     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1921)
....
W/System.err: Caused by: software.amazon.awssdk.crt.mqtt.MqttException: System call failureW/System.err:     at software.amazon.awssdk.crt.mqtt.MqttClientConnection.onConnectionComplete(MqttClientConnection.java:142)
-----
2. When endpoint URL is incorrect 
W/System.err: java.util.concurrent.ExecutionException: software.amazon.awssdk.crt.mqtt.MqttException: TLS (SSL) negotiation failed
W/System.err:     at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:359)
W/System.err:     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1921)
....
W/System.err: Caused by: software.amazon.awssdk.crt.mqtt.MqttException: TLS (SSL) negotiation failed
W/System.err:     at software.amazon.awssdk.crt.mqtt.MqttClientConnection.onConnectionComplete(MqttClientConnection.java:142)
--------
3. With invalid certificate (certificate is not valid)
W/System.err: software.amazon.awssdk.crt.CrtRuntimeException: TlsContext.tls_ctx_new: Failed to create new aws_tls_ctx (aws_last_error: AWS_IO_TLS_CTX_ERROR(1033), Failed to create tls context)
W/System.err:     at software.amazon.awssdk.crt.io.TlsContext.tlsContextNew(Native Method)
W/System.err:     at software.amazon.awssdk.crt.io.TlsContext.<init>(TlsContext.java:34)
W/System.err:     at software.amazon.awssdk.crt.io.ClientTlsContext.<init>(ClientTlsContext.java:36)
W/System.err:     at software.amazon.awssdk.iot.AwsIotMqttConnectionBuilder.build(AwsIotMqttConnectionBuilder.java:401)
....
--------
4. With incorrect certificate (certificate is not allowed for connection)
W/System.err: java.util.concurrent.ExecutionException: software.amazon.awssdk.crt.mqtt.MqttException: Mqtt operation interrupted by connection shutdown
W/System.err:     at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:359)
W/System.err:     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1921)
....
 W/System.err: Caused by: software.amazon.awssdk.crt.mqtt.MqttException: Mqtt operation interrupted by connection shutdown
-----
5. With incorrect Root CA
W/System.err: java.util.concurrent.ExecutionException: software.amazon.awssdk.crt.mqtt.MqttException: TLS (SSL) negotiation failed
W/System.err:     at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:359)
W/System.err:     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1921)
....
W/System.err: Caused by: software.amazon.awssdk.crt.mqtt.MqttException: TLS (SSL) negotiation failed
W/System.err:     at software.amazon.awssdk.crt.mqtt.MqttClientConnection.onConnectionComplete(MqttClientConnection.java:142)
-----
Please let me know in case more information required.

**Comment by jmklix** [comment]
You won't be able to see the disconnect reason on the client side, because in the MQTT protocol the connection is dropped without sending a reason to the client. You can check the CloudWatch logs to see the cause of the connection failure. To enable CloudWatch logs look [here](https://docs.aws.amazon.com/iot/latest/developerguide/cloud-watch-logs.html).

**Comment by codegame6** [comment]
Some of the information is important for client side for user experience. Based on this information android application take required action like if certificates are invalid then it can show an indication to the user and it should not retry to connect but if it is something to do with the network then it can retry in the background and there can be other use-cases as well.
I can see an error in exception as I mentioned on the above logs. Is it possible to share the error number as well or some document saying error in each condition? So that AWS IoT Device SDK users can know the correct status and take necessary action.

**Comment by codegame6** [comment]
Is there anything already available or can be added?

**Comment by jmklix** [comment]
No, there is nothing currently available. But I do agree it is something that can be added to help diagnose connection failures.

**Comment by codegame6** [comment]
Is it possible to make getErrorCode public from MqttException or provide a different approach to provide error codes? This will help us to take appropriate action based on the error codes. Currently, all the errors are reported as MqttException with different error strings which cannot be used to take actions for different errors.

**Comment by jmklix** [comment]
MQTT 5 has added reason codes to its connection events. This will allow you to get a better idea of why the connection is failing. Check out the [AWS MQTT documentation](https://docs.aws.amazon.com/iot/latest/developerguide/mqtt.html) and our [MQTT 5 sample](https://github.com/aws/aws-iot-device-sdk-java-v2/blob/main/samples/Mqtt5/PubSub/src/main/java/pubsub/PubSub.java) for more info about this. 

Below are some of the reason codes that you can see in MQTT 5

CONNACK Reason Codes
--
Value | Hex | Reason Code name | Description
-- | -- | -- | --
| 0 | 0x00 | Success | The connection is accepted. |
| 128 | 0x80 | Unspecified error | The server does not wish to reveal the reason for the failure, or none of the other reason codes apply. |
| 133 | 0x85 | Client Identifier not valid | The client identifier is a valid string but is not allowed by the server. |
| 134 | 0x86 | Bad User Name or Password | The server does not accept the user name or password specified by the client. |
| 135 | 0x87 | Not authorized | The client is not authorized to connect. |
| 144 | 0x90 | Topic Name invalid | The Will Topic Name is correctly formed but is not accepted by the server. |
| 151 | 0x97 | Quota exceeded | An implementation or administrative imposed limit has been exceeded. |
| 155 | 0x9B | QoS not supported | The server does not support the QoS set in Will QoS. |
