### ISSUE TITLE
Does auto reconnect works same as before?

### ISSUE THREAD

**Issue by waah42** [aws/aws-iot-device-sdk-java-v2#108]
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Android, with OS version 11 on Pixel 3a

**Describe the question**
We are migrating from `{com.amazonaws:aws-android-sdk-iot:2.16.3 ,com.amazonaws:aws-android-sdk-core:2.16.3}`  to `software.amazon.awssdk.iotdevicesdk:android:1.2.9`

We were using `autoReconnect = true` (https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L134), I couldn't find something similar in the new api. 

**Impact:** 
In case when the app starts and there is no internet connectivity, the connection doesn't change to successful automatically.

Can someone please point me to configuration for the v2 sdk to have the same auto-reconnect functionality? 
If that’s not possible in the v2 sdk at the moment, will it be added in future versions?

**Comment by bretambrose** [comment]
If the initial connection attempt fails, no attempts to reconnect will be made.  If the initial connection attempt succeeds, reconnect will be done automatically (with exponential backoff) indefinitely.

I don't know of any plans to add any additional options with respect to reconnecting though.

**Comment by waah42** [comment]
> If the initial connection attempt fails, no attempts to reconnect will be made.

yes but that wasn't the case before with the old SDK versions. It makes migrating a bit harder because now we have to handle that the initial connects failures ourselves but not the subsequent ones.

**Comment by bretambrose** [comment]
To be honest, Amplify/Android SDK are a different organization and I'm not aware of their SDK behavioral properties.  As far as I know, the v1 IoT SDKs all throw exceptions/errors on initial connect failures.

**Comment by waah42** [comment]
Alright 👍 , just to make sure one more time, the new `aws-iot-device-sdk-java-v2` is the way forward right and previous SDKs are just in BugFixes but no new features mode?

**Comment by bretambrose** [comment]
That is correct, yes.
