### ISSUE TITLE
Client using custom authorizer unable to receive messages, but cert client can

### ISSUE THREAD

**Issue by webermaster** [aws/aws-iot-device-sdk-java-v2#113]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Known Issue**
- [X] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
We are attempting to use RawPubSub with a custom authorizer to publish and receive. 

When they use a certificate and the BasicPubSub, connect/publish/subscribe/receive works as expected. 

When they use a custom authorizer that returns the same policy, connect/publish/subscribe works as expected but no messages are received. Even a policy allowing all AWSIOT operations on all resources (action: iot:*, resource:*) resulted in no messages being received.

We are returning the same policy text in the custom authorizer as they had in the certificate but there are no messages received or errors thrown, however a subscription is stil establish per $aws/event/subscribe/#

**SDK version number**
built from tag v1.2.8

**Platform/OS/Hardware/Device**
What are you running the sdk on? Mac OSX 10.15.7

**To Reproduce (observed behavior)**

- checkout git tag v1.2.8
- make RawPubSub.java and PubSub.java classes public 
- remove publish block from RawPubSub.java
- remove subscribe block from PubSub.java
- build sdk and both samples via `mvn clean install`
- create default custom authorizer that returns following policy:
```json
{
	'Version': '2012-10-17',
	'Statement': [{
		'Effect': 'Allow',
		'Action': ['iot:Connect'],
		'Resource': ['arn:aws:iot:us-east-2:ACCOUNT:client/CLIENTID']
	}, {
		'Effect': 'Allow',
		'Action': ['iot:Subscribe'],
		'Resource': ['arn:aws:iot:us-east-2:ACCOUNT:topicfilter/iot-2/type/*/id/CLIENTID/cmd/*']
	}, {
		'Effect': 'Allow',
		'Action': ['iot:Receive'],
		'Resource': ['arn:aws:iot:us-east-2:ACCOUNT:topic/iot-2/type/*/id/CLIENTID/cmd/*']
	}, {
		'Effect': 'Allow',
		'Action': ['iot:Publish'],
		'Resource': ['arn:aws:iot:us-east-2:ACCOUNT:topic/iot-2/type/*/id/CLIENTID/evt/*']
	}]
}
```
create a "Thing" with the following policy:
```json
{
	'Version': '2012-10-17',
	'Statement': [{
		'Effect': 'Allow',
		'Action': ['iot:Connect'],
		'Resource': ['arn:aws:iot:us-east-2:ACCOUNT:client/CLIENTID']
	}, {
		'Effect': 'Allow',
		'Action': ['iot:Subscribe'],
		'Resource': ['arn:aws:iot:us-east-2:ACCOUNT:topicfilter/iot-2/type/*/id/CLIENTID/evt/*']
	}, {
		'Effect': 'Allow',
		'Action': ['iot:Receive'],
		'Resource': ['arn:aws:iot:us-east-2:ACCOUNT:topic/iot-2/type/*/id/CLIENTID/evt/*']
	}, {
		'Effect': 'Allow',
		'Action': ['iot:Publish'],
		'Resource': ['arn:aws:iot:us-east-2:ACCOUNT:topic/iot-2/type/*/id/CLIENTID/cmd/*']
	}]
}
```

execute the following commands in separate terminals:
```
mvn exec:java -pl samples/RawPubSub -Dexec.mainClass=rawpubsub.RawPubSub -Dexec.args='--endpoint <blah>-ats.iot.us-east-2.amazonaws.com --rootca AmazonRootCA1.pem --username CLIENTID --password PASSWORD --clientId CLIENTID --topic iot-2/type/WP/id/CLIENTID/cmd/foobar'

mvn exec:java -pl samples/PubSubStress -Dexec.mainClass=pubsubstress.PubSubStress -Dexec.args='--endpoint <blah>-ats.iot.us-east-2.amazonaws.com --rootca ca.pem --cert cert.pem --key key.pem --clientId CLIENTID --topic iot-2/type/WP/id/CLIENTID/cmd/foobar'
```

Observe in the test console that the RawPubSub will connect and subscribe but it does not print any messages to the terminal and completes without error

**Expected behavior**
RawPubSub should print messages to the terminal

**Comment by webermaster** [comment]
It turns out that the main thread simply wasn't waiting for the subscriber to read all the messages before closing the MQTT connection and exiting.

Submitted a pull request to fix this in RawPubSub and BasicPubSub: https://github.com/aws/aws-iot-device-sdk-java-v2/pull/114

**Comment by jmklix** [comment]
Thanks for taking the time to make a pull request. Any further comments regarding this will be discussed on the PR.
