### ISSUE TITLE
Exception encountered: software.amazon.awssdk.crt.CrtRuntimeException: TlsContext.tls_ctx_new: Failed to create new aws_tls_ctx (aws_last_error: AWS_IO_TLS_CTX_ERROR(1033), Failed to create tls context)

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [aws/aws-iot-device-sdk-java-v2#118]
Just wanted to let you know that the sample program in this example [Dec 08, 2020], as is not working, producing below error. Is this library good for production use?

Exception encountered: software.amazon.awssdk.crt.CrtRuntimeException: TlsContext.tls_ctx_new: Failed to create new aws_tls_ctx (aws_last_error: AWS_IO_TLS_CTX_ERROR(1033), Failed to create tls context)

I see that the exception coming from a JNI call. 

Mint Linux V. 20, 64 bit

Found that the certificate downloaded had "undefined" in download file. 

Deleted and regenerated the certificate and device , now it is working .closing this issue.

**Comment by gopalakrishnan-subramani** [comment]
Issue with certificate file

**Comment by Devoamos** [comment]
@gopalakrishnan-subramani - What was the issue with the certificate file? I have a similar issue

`TlsContext.tls_ctx_new: Failed to create new aws_tls_ctx (aws_last_error: AWS_ERROR_SUCCESS(0), Success.)`
