### ISSUE TITLE
Support for older ARM processors. 

### ISSUE THREAD

**Issue by mark-shea** [aws/aws-iot-device-sdk-java-v2#126]
Is it possible to add support for older ARM processors to the SDK and CRT?  Such as Arm926EJ-S which is based on ARM v5 architecture?

We are currently using the V1 Java SDK and would like to upgrade to V2, however the SDK and CRT do not support our processor.  This issue is related to AWS support ticket 7817113101.

**Comment by jmklix** [comment]
Yes, this is something that we would like to add. I have added it to our backlog, but I can't give a timeline for when it will be completed.

**Comment by jmklix** [comment]
Sorry, but this is something that we no longer are planning to adding support for due to resource constraints
