### ISSUE TITLE
Doesn't work with AWS credentials providers (e.g Cognito)

### ISSUE THREAD

**Issue by sandyscoffable** [aws/aws-iot-device-sdk-java-v2#127]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**

Unable to use Cognito as a credentials provider for this library (at least straightforwardly) on Android

**SDK version number**

```
    implementation 'software.amazon.awssdk.iotdevicesdk:aws-iot-device-sdk:1.2.11'
    implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.22.0'
```

**Platform/OS/Hardware/Device**

Android Studio 4
Mac OSX
Android 10

**To Reproduce (observed behavior)**

Initialise the cognito credentials provider. Plug that into the IoT MQTT Builder (compile error, `AWSCredentialsProvider` != `CredentialsProvider`
```
        val awsCredentialsProvider : AWSCredentialsProvider = CognitoCachingCredentialsProvider(
            context,
            "eu-west-1:xxxx-xxxxx-xxxxx-xxxx",  
            Regions.EU_WEST_1
        )
        

        val builder = AwsIotMqttConnectionBuilder.newDefaultBuilder().
            withWebsocketCredentialsProvider(awsCredentialsProvider) // This takes CredentialsProvider, not AWSCredentialsProvider
            .build()
```

At this juncture, I'm like ... oookkkkaaaaay ... I'll just extend `CredentialsProvider` with a custom class and provide some bridging code so I can join these two disparate AWS objects together since they are effectively the same thing ... i.e something like:
```
class CustomCognitoCredentialsProvider(val cognitoCachingCredentialsProvider: CognitoCachingCredentialsProvider) : CredentialsProvider() {

    override fun getCredentials(): CompletableFuture<Credentials> {

        val completableFuture = CompletableFuture<Credentials>()

        val awsSessionCredentials =  cognitoCachingCredentialsProvider.credentials

        completableFuture.complete(Credentials(awsSessionCredentials.awsAccessKeyId.toByteArray(),
            awsSessionCredentials.awsSecretKey.toByteArray(),
            awsSessionCredentials.sessionToken.toByteArray()))

        return completableFuture
    }

}
```

Result: Futures are only supported in Android >= 7.0, so I can't do that either.

**Expected behavior**

Should be able to plumb in an AWSCredentialsProvider, like most other AWS libraries.

**Logs/output**

n/a

**Additional context**

The only solution for us was to move back to v1 of the device SDK (which we do use elsewhere)

**Comment by bretambrose** [comment]
We still have some work left to do in our provider support which includes both cognito-sourced credentials and a native provider that can invoke a third party provider via an interface.

That being said, I don't see the completable-future-basis of the API changing.

**Comment by sandyscoffable** [comment]
Thanks for the reply. v1 of the library is working for us right now 👍

**Comment by sbSteveK** [comment]
Cognito support for aws-crt-java was added in v0.19.4 and aws-iot-device-sdk-java-v2 v1.10.5

A Cognito sample is available here: https://github.com/aws/aws-iot-device-sdk-java-v2/tree/main/samples/CognitoConnect

Closing this issue. Please feel free to reopen or comment if there's still a problem.
