### ISSUE TITLE
Code comments

### ISSUE THREAD

**Issue by msoldin** [aws/aws-iot-device-sdk-java-v2#128]
**Is your feature request related to a problem? Please describe.**
Some definitions are very unclear, for example what is a ClientsBootstrap or an EventLoopGroup (meanwhile i figured that out). Above that what are minimum requirements to create a MQTT-Connection. There is just no information about what are these methods doing. I think this is a very important information at all.

**Describe the solution you'd like**
There should be a short description for every method to insure a good quality and a good understanding for users of this project.

**Describe alternatives you've considered**
An alternative was the old java-client, but it get no more updates. I can't argument this in my current Project, so i have to stick to the newer one. But the older was is more easily to understand and it's full of comments explaining everything.

**Comment by pconroy328** [comment]
The lack of Javadocs is surprising.

**Comment by jmklix** [comment]
Thanks for pointing this out. This is something that we plan on adding, but I am closing this issue in favor of this similar one: https://github.com/aws/aws-iot-device-sdk-java-v2/issues/100
