### ISSUE TITLE
SubscribeToTopic: blobs are mutated and not RFC4648 compliant

### ISSUE THREAD

**Issue by cthulhuology** [aws/aws-iot-device-sdk-java-v2#136]
In trying to connect to Greengrass v2 via an unsupported language, I encountered a surprising encoding issue blobs.  For reference the Github issue for greengrass v2 is here:

https://github.com/aws-greengrass/aws-greengrass-nucleus/issues/864

The core issue is when you publish a simple message like "hello world" to a local topic using a message like:

{ "topic": "test/topic", "publishMessage": {"binaryMessage" : { "message" : "aGVsbG8gd29ybGQ=" }}}

The subscriber receives the message

{ "binaryMessage": {"message":"aGVsbG8gd29ybGQ\u003d"}}

While this is valid JSON, the message payload is not a valid base64 encoded string according to RFC4648.  Instead, one must double decode the string value, first by decoding the unnecessarily encoded UTF8 code points, (there may be multiple if more characters of padding are required).  

This clearly also violates the principle of least surprise as the output value is mutated from the value sent by the publisher.  When I publish a message via an IPC / RPC mechanism I expect to get the same value out, not some arbitrarily transformed equivalent.

It should be noted that the deserialization of the serivceModel cause the entire blob to both be decoded and re-encoded when passing between components.  This produces large unnecessary memory and processing overheads for certain workloads.  As the base64 encoding already incurs a 33% size overhead, this additional encoding/decoding step also incurs additional overhead on the consumer who must now once again buffer and decode the needlessly encoded code point.

**Comment by DavidOgunsAWS** [comment]
I think you may have a double-quote typo in the subscribe received. Given the presumptive typo-fixed: `{"binaryMessage": {"message":""aGVsbG8gd29ybGQ\u003d"}}` is properly encoded JSON. The content between the quotes is encoded JSON however and not ready for base64 decoding until it is first JSON decoded.

This is the result of just JSON decoding:
```
$ echo '{"binaryMessage": {"message":"aGVsbG8gd29ybGQ\u003d"}}' | jq -r .binaryMessage.message
aGVsbG8gd29ybGQ=
```

And the combination of JSON decoding and then base64 decoding:
```
$ echo '{"binaryMessage": {"message":"aGVsbG8gd29ybGQ\u003d"}}' | jq -r .binaryMessage.message | base64 -d
hello world
```

As for the efficiency of dong this, it is not great but it is necessary when encoding bytes into test formats like XML or JSON. There was no reason to reinvent the wheel here.

**Comment by cthulhuology** [comment]
In EventStreamRPCServiceModel

https://github.com/aws/aws-iot-device-sdk-java-v2/blob/747beba7b759ec652895d54b1f839d153a26cc20/sdk/greengrass/event-stream-rpc-model/src/main/java/software/amazon/awssdk/eventstreamrpc/EventStreamRPCServiceModel.java#L39

a gson builder is instantiated that is shared across service models.  But you don't disable HTML escaping:

https://github.com/google/gson/blob/ceae88bd6667f4263bbe02e6b3710b8a683906a2/gson/src/main/java/com/google/gson/GsonBuilder.java#L410

If you invoke this disable it will avoid doing the unnecessary encoding done here:

https://github.com/google/gson/blob/ceae88bd6667f4263bbe02e6b3710b8a683906a2/gson/src/main/java/com/google/gson/stream/JsonWriter.java#L143

which given that the code in question is exchanging opaque blobs between components, the HTML escaping doesn't seem at all relevant to the discussion. 

Further more, in the IoTJobsClientWrapper,

https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/67e2f79b0e77170fa32798e30498712497342cda/src/main/java/com/aws/greengrass/deployment/IotJobsClientWrapper.java#L76

greengrass  does exactly this.   From the perspective of someone writing components with what is known to be by spec a base64 encoded payload, I shouldn't even need to parse the JSON object, but should be able to rely that the UTF-8 string is a properly encoded base64 value.  Now I can write a zero copy work around for this buffer, but this seems to be very much unnecessary, and the underlying serialization library already supports turning this unnecessary work off.  Doing so would make working with blobs slightly more efficient, and put fewer requirements on the consumers.  

It should also be noted that, the EventStreamJsonMessage already does no validate the output, and directly uses this gson object for producing nothing more than a UTF-8 encoded byte array.

https://github.com/aws/aws-iot-device-sdk-java-v2/blob/747beba7b759ec652895d54b1f839d153a26cc20/sdk/greengrass/event-stream-rpc-model/src/main/java/software/amazon/awssdk/eventstreamrpc/model/EventStreamJsonMessage.java#L12

**Comment by DavidOgunsAWS** [comment]
That code comment is referring to the Greengrass IPC model object's validity. Validity such as: are all required fields present, or does a string validate against a regex. There is trust that Gson is outputting valid JSON if it didn't throw an exception, so we aren't running further validation on that end.

I understand the efficiency issue by having escape characters inside a JSON blob, but at this point client (and server) implementations exist that produce the escaped characters anywhere in the JSON structure including blobs. Any client that cannot handle escaped characters anywhere will be broken with existing peers.
