### ISSUE TITLE
Not able to connect to AWS-IoT with custom CA and just-in-time-registration

### ISSUE THREAD

**Issue by lbeuster** [aws/aws-iot-device-sdk-java-v2#140]
**Is your feature request related to a problem? Please describe.**
I created a custom CA at AWS IoT, created a key value pair and activated just-in-time-registration for this CA. But I found no working solution for aws-iot to connect to AWS and activate the registration. The custom CA must be a part of the "keystore" but for me it seems like the existing CA-options only apply for the "truststore".
I could activate the registration with paho, hivemq und mosquitto cli - but not with aws-iot.

**Describe the solution you'd like**
A config option to activate the CA for the keystore.

**Comment by jmklix** [comment]
Can you provide clarification on what you are trying to do?
