### ISSUE TITLE
Not able to connect to AWS-IoTusing self signed certificate which is registerd in AWS IoT core 

### ISSUE THREAD

**Issue by PU00165** [aws/aws-iot-device-sdk-java-v2#146]
Confirm by changing [ ] to [x] below:
- I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and found few solutions which said that we need to pass on right root CA
-
What are you running the sdk on? Windows 10 machine I am trying to connect to IoT where I am using the RawPubSub.java class and I am passing args are below.

clientId = "PCMA4GMULTIACCT" 
rootCaPath = "C:\\Users\\pu00165\\Documents\\GitHub_New\\aws-iot-device-sdk-java-v2\\samples\\RawPubSub\\SFSRootCAG2.pem"
certPath = "C:\\Users\\pu00165\\Documents\\GitHub_New\\aws-iot-device-sdk-java-v2\\samples\\RawPubSub\\iotmultiacct.crt"
keyPath= "C:\\Users\\pu00165\\Documents\\GitHub_New\\aws-iot-device-sdk-java-v2\\samples\\RawPubSub\\iotmultiacct.key"
endpoint = "a2eg3przjv23yh-ats.iot.us-east-1.amazonaws.com"
topic = "yukon/v1/t2h/21/392/PCMA4GMULTIACCT"

**Describe the question**

I am trying to use AWS iot sdk 2 (https://github.com/aws/aws-iot-device-sdk-java-v2 ) for java to implement an IoT client.

I am referring to https://github.com/aws/aws-iot-device-sdk-java-v2/blob/main/samples/RawPubSub/src/main/java/rawpubsub/RawPubSub.java  class to implement the client. 

To get the rootCA details I have referred to https://docs.aws.amazon.com/iot/latest/developerguide/server-authentication.html#server-authentication-certs .

However, as I am trying to connect I am getting below exception.

Here the certificate which I am using to connect with the thing (arn:aws:iot:us-east-1:637306973112:thing/PCMA4GMULTIACCT) is registered in AWS.

Caused by: java.util.concurrent.ExecutionException: software.amazon.awssdk.crt.mqtt.MqttException: TLS (SSL) negotiation failed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at rawpubsub.RawPubSub.main(RawPubSub.java:95)
	... 5 more
Caused by: software.amazon.awssdk.crt.mqtt.MqttException: TLS (SSL) negotiation failed
	at software.amazon.awssdk.crt.mqtt.MqttClientConnection.onConnectionComplete(MqttClientConnection.java:133)

I have reached out to AWS Support (Premium) and they to tried connecting to IoT using RawPubSub and are also facing the same issue. Can you please help here?

**Comment by bretambrose** [comment]
What are the cryptographic properties of the key you're using?
Can you attach trace logs of the connection attempt?

**Comment by manikantabandaru** [comment]
Hi @bretambrose ,
I too face similar problem but the greengrass is running on ubuntu.

Attaching the trace logs for same. I see TLS negotiation error for connection  
[trace.txt](https://github.com/aws/aws-iot-device-sdk-java-v2/files/6173664/trace.txt)

**Comment by bretambrose** [comment]
A packet capture from wireshark of the tls handshake might shed some more light on what's going wrong (https://github.com/aws/s2n-tls/blob/e6eaf873543cf27583ac96e006064f0582ce3a97/tls/s2n_handshake_io.c#L1105)

Also, relative to the original poster, unless you're using your own registered CA, AmazonRootCA1.pem is typically enough for certificates generated through the IoT console or programatically.

**Comment by manikantabandaru** [comment]
@bretambrose  Thanks for reply.  I am using certificate generated from console but still got this problem. Also I verified the certificates with openssl cmd and it worked fine.
I will try to get wireshark logs

**Comment by DavidOgunsAWS** [comment]
Seeing the filename "C:\Users\pu00165\Documents\GitHub_New\aws-iot-device-sdk-java-v2\samples\RawPubSub\SFSRootCAG2.pem" as the rootCA suggests something other than one of the Amazon rootCAs is being used. Why rename the file? Can you describe what that CA's contents are? If it is anything other than a rename of AmazonRootCA1 or AmazonRootCA3 then that may likely be the problem. Not specifying any CA at all may work as it will result in using your OS platform CA.

**Comment by manikantabandaru** [comment]
@bretambrose  
Apologies for late response.
Please find the attached wireshark logs . Also the Certificates are working proper when tested with Openssl cmd for handshake test

[logs-wire.zip](https://github.com/aws/aws-iot-device-sdk-java-v2/files/6242297/logs-wire.zip)

**Comment by bretambrose** [comment]
I think this issue is now conflating two separate ones.  The original was with a self-signed/custom CA, but the replies are about an issue with a console-generated certificate.  @manikantabandaru Can you create a separate issue, include the code you are using for initializing the TlsContext, and verify that the CA you're setting is simply a rename of AmazonRootCA1.pem.  Alternatively, you can just drop initializing the root CA entirely since AmazonRootCA1 is present in almost all system cert stores (other than Android).

**Comment by jmklix** [comment]
@PU00165 in addition to the questions listed above can you include the steps you used to create and register the self signed cert?
