### ISSUE TITLE
 No implementation found for void software.amazon.awssdk.crt.CRT.awsCrtInit

### ISSUE THREAD

**Issue by hungnd2126** [aws/aws-iot-device-sdk-java-v2#150]
I'm trying to build the mobile app to using **aws-crt-java** from **software.amazon.awssdk.crt:aws-crt:0.11.5**
but the system throws the message "No implementation found for void software.amazon.awssdk.crt.CRT.awsCrtInit"

**Describe the bug**
This is the stack trace from running the application:
`W/System.err: java.io.IOException: Unable to open library in jar for AWS CRT: /android/x86/libaws-crt-jni.so
W/System.err:     at software.amazon.awssdk.crt.CRT.loadLibraryFromJar(CRT.java:155)
W/System.err:     at software.amazon.awssdk.crt.CRT.<clinit>(CRT.java:32)
W/System.err:     at software.amazon.awssdk.crt.CrtResource.<clinit>(CrtResource.java:95)
W/System.err:     at pubsub.PubSub.main(PubSub.java:237)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at software.amazon.awssdk.iotsamples.MainActivity$runSample$1.invoke(MainActivity.kt:151)
W/System.err:     at software.amazon.awssdk.iotsamples.MainActivity$runSample$1.invoke(MainActivity.kt:24)
W/System.err:     at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
E/ssdk.iotsample: No implementation found for void software.amazon.awssdk.crt.CRT.awsCrtInit(int, boolean) (tried `

I found the same issue about **_CRT.awsCrtInit_** the and SDK have some conflict about version
so in lasted **aws-iot-device-sdk-java-v2** and **software.amazon.awssdk.crt:aws-crt:0.11.5** have same root cause at here?
I still hope to use X509 to connect my android app to Iotcore.

**Platform/OS/Hardware/Device**
I'm using Pixel 4 XL

**Comment by jmklix** [comment]
What steps are you using to build this sdk?
What version of this sdk are you using?
Are you just trying to run the unmodified pubsub?
