### ISSUE TITLE
Amazon AWS IoTDeviceAdvisor Connection with  Native Android Application

### ISSUE THREAD

**Issue by roheru** [aws/aws-iot-device-sdk-java-v2#151]
Hi Everybody
How are things?, I have a some problem with communication with native android application and AWSDeviceAdvisor, because to due the fact that I use AWSIoTMqttManager for connection with AWS amazon Device advisor (this endpoint for this XXXXXXXX.deviceadvisor.iot.us-east-1.amazonaws.com), the console message shown me "Bad endpoint format". However when I use IoT endpoint XXXXXXXX.iot.us-east-1.amazonaws.com I' haven't got any problem, Can you help me? please

The snippet code for connection is given below:
**mqttManager = new AWSIotMqttManager(clientId , CUSTOMER_SPECIFIC_ENDPOINT);**

Android SDK

**Device Information**

Device: Genymotion, Android Studio
Android Version: minSdkVersion="10"
Specific to simulators: Genymotion

**Comment by bretambrose** [comment]
I think you may have the wrong repo for the SDK you're using.  You may be looking for https://github.com/aws-amplify/aws-sdk-android
