### ISSUE TITLE
socket is closed

### ISSUE THREAD

**Issue by keshaojie** [aws/aws-iot-device-sdk-java-v2#169]
In samples / basic PubSub, I have configured rootpath, certpath, keypath and endpoint. But after running, an error is reported: "socket is closed" and a solution is requested

Exception in thread "main" java.lang.RuntimeException: Exception occurred during connect
	at pubsub.PubSub.main(PubSub.java:298)
Caused by: java.util.concurrent.ExecutionException: software.amazon.awssdk.crt.mqtt.MqttException: socket is closed.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at pubsub.PubSub.main(PubSub.java:295)
Caused by: software.amazon.awssdk.crt.mqtt.MqttException: socket is closed.
	at software.amazon.awssdk.crt.mqtt.MqttClientConnection.onConnectionComplete(MqttClientConnection.java:139)

**Comment by jmklix** [comment]
Does your execution command look something line this:

``` sh
mvn exec:java -pl samples/BasicPubSub -Dexec.mainClass=pubsub.PubSub -Dexec.args='--endpoint <prefix>-ats.iot.<region>.amazonaws.com --clientId sdk-java --topic sdk/test/java --rootca <path to rootca> --cert <path to cert> --key <path to key>' 
```

Can you also please file out the info requested in the template below:


**Describe the bug**
A clear and concise description of what the bug is.

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the sdk on?

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
-Daws.crt.debugnative=true
-Daws.crt.log.destination=File
-Daws.crt.log.level=Trace
-Daws.crt.log.filename=<path and filename>
```

**Additional context**
Add any other context about the problem here.

**Comment by keshaojie** [comment]
> Does your execution command look something line this:
> 
> ```shell
> mvn exec:java -pl samples/BasicPubSub -Dexec.mainClass=pubsub.PubSub -Dexec.args='--endpoint <prefix>-ats.iot.<region>.amazonaws.com --clientId sdk-java --topic sdk/test/java --rootca <path to rootca> --cert <path to cert> --key <path to key>' 
> ```
> 
> Can you also please file out the info requested in the template below:
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **SDK version number**
> 
> **Platform/OS/Hardware/Device**
> What are you running the sdk on?
> 
> **To Reproduce (observed behavior)**
> Steps to reproduce the behavior (please share code)
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Logs/output**
> If applicable, add logs or error output.
> 
> To enable logging, set the following system properties:
> 
> _REMEMBER TO SANITIZE YOUR PERSONAL INFO_
> 
> ```
> -Daws.crt.debugnative=true
> -Daws.crt.log.destination=File
> -Daws.crt.log.level=Trace
> -Daws.crt.log.filename=<path and filename>
> ```
> 
> **Additional context**
> Add any other context about the problem here.

**Comment by keshaojie** [comment]
> Does your execution command look something line this:
> 
> ```shell
> mvn exec:java -pl samples/BasicPubSub -Dexec.mainClass=pubsub.PubSub -Dexec.args='--endpoint <prefix>-ats.iot.<region>.amazonaws.com --clientId sdk-java --topic sdk/test/java --rootca <path to rootca> --cert <path to cert> --key <path to key>' 
> ```
> 
> Can you also please file out the info requested in the template below:
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **SDK version number**
> 
> **Platform/OS/Hardware/Device**
> What are you running the sdk on?
> 
> **To Reproduce (observed behavior)**
> Steps to reproduce the behavior (please share code)
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Logs/output**
> If applicable, add logs or error output.
> 
> To enable logging, set the following system properties:
> 
> _REMEMBER TO SANITIZE YOUR PERSONAL INFO_
> 
> ```
> -Daws.crt.debugnative=true
> -Daws.crt.log.destination=File
> -Daws.crt.log.level=Trace
> -Daws.crt.log.filename=<path and filename>
> ```
> 
> **Additional context**
> Add any other context about the problem here.

Describe the bug
caused by:software.amazon.awssdk.crt.mqtt.Mqttexception:Hostname was invalid for dns resolution
sdk version
https://docs.aws.amazon.com/zh_cn/iot/latest/developerguide/iot-sdks.html
Platform/OS/Hardware/Device
on windows7
Expected behavior
to conent aws iot core

**Comment by bretambrose** [comment]
Could you attach trace level logs per the template?
