### ISSUE TITLE
software.amazon.awssdk.crt.mqtt.MqttException: The connection was closed unexpectedly.

### ISSUE THREAD

**Issue by highergao** [aws/aws-iot-device-sdk-java-v2#187]
Confirm by changing [ ] to [x] below:
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?

**Describe the question**

**Comment by jmklix** [comment]
Can you provide more details about the error that you are getting and how to reproduce it?

Also make sure policy for your IoT thing has the correct permissions to allow what you are trying to do.

**Comment by highergao** [comment]
1，first ,i create a thing ,Certificates and policy 
   this my aws-cli script 
> `
aws iot create-thing --thing-name "MyIotThing-window"
{
    "thingName": "MyIotThing-window",
    "thingArn": "arn:aws:iot:us-east-1:357550993143:thing/MyIotThing-window",
    "thingId": "9566d894-8b6d-40ee-a184-f8217e0e4d60"
}
curl -o C:\Users\gaohw6\certs\Amazon-root-CA-1.pem  https://www.amazontrust.com/repository/AmazonRootCA1.pem 
aws iot create-keys-and-certificate  --set-as-active --certificate-pem-outfile "C:\Users\gaohw6\certs\device.pem.crt"   --public-key-outfile "C:\Users\gaohw6\certs\public.pem.key"  --private-key-outfile "C:\Users\gaohw6\certs\private.pem.key"

aws iot attach-thing-principal  --thing-name "MyIotThing-window" --principal "arn:aws:iot:us-east-1:357550993143:cert/829d9956c714a6915673b7ad8344613781aa69478b5beddb55abf63a902db776"

aws iot create-policy  --policy-name "MyIotThingPolicy-window" --policy-document "C:\Users\gaohw6\policy.json"
`
this i the content of policy.json

`
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish",
        "iot:Receive"
      ],
      "Resource": [
        "arn:aws:iot:us-east-1:357550993143:topic/test/topic"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Subscribe"
      ],
      "Resource": [
        "arn:aws:iot:us-east-1:357550993143:topicfilter/test/topic"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Connect"
      ],
      "Resource": [
        "arn:aws:iot:us-east-1:357550993143:client/test-*"
      ]
    }
  ]
}
`
this is my java code 

`
 public static void main(String[] args) throws GeneralSecurityException, ExecutionException, InterruptedException {
        MqttClientConnection connection = getConnection("MyIotThing-window");
        CompletableFuture<Boolean> connect = connection.connect();
        Boolean aBoolean = connect.get();
        System.out.println(aBoolean);
    }
    private static MqttClientConnection getConnection(String deviceId) throws GeneralSecurityException {

        String certificatePem = getStringFromFilePath("C:\\Users\\gaohw6\\certs\\device.pem.crt");
        String privateKeyPem = getStringFromFilePath("C:\\Users\\gaohw6\\certs\\private.pem.key");

        try (EventLoopGroup eventLoopGroup = new EventLoopGroup(1);
             HostResolver resolver = new HostResolver(eventLoopGroup);
             ClientBootstrap clientBootstrap = new ClientBootstrap(eventLoopGroup, resolver);
             AwsIotMqttConnectionBuilder builder =
                     AwsIotMqttConnectionBuilder.newMtlsBuilder(
                             certificatePem, privateKeyPem)) {

            builder
                    .withBootstrap(clientBootstrap)
                    .withClientId(deviceId)
                    .withEndpoint("a12d9gvlolziih-ats.iot.us-east-1.amazonaws.com");
            return builder.build();
        }
    }
`

**Comment by highergao** [comment]
maybe,  my device.pem,crt is error
