### ISSUE TITLE
Basic PubSub example can't connect

### ISSUE THREAD

**Issue by jonyt** [aws/aws-iot-device-sdk-java-v2#189]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Known Issue**
- [x ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
When adding a lastWill message the SDK can't connect.

**SDK version number**
1.5.3

**Platform/OS/Hardware/Device**
Windows 10

**To Reproduce (observed behavior)**
Similarly to #188 I'm using the basic pubsub example and adding the line `.withWill(new MqttMessage("topic", "aaa".getBytes(java.nio.charset.StandardCharsets.UTF_8)), QualityOfService.AT_LEAST_ONCE, true)` to the connection builder.  Running the application with `java -jar target\BasicPubSub-1.0-SNAPSHOT-jar-with-dependencies.jar --clientId the-thing --x509rootca root-CA.crt --x509cert cert.pem --x509key cert.private_key --endpoint xxxxxxxxxxx-ats.iot.eu-west-1.amazonaws.com --count 5 -w --region eu-west-1 --x509 --x509rolealias iot-device-authorization-role-alias --x509endpoint xxxxxxxx.credentials.iot.eu-west-1.amazonaws.com --x509thing the-thing -m yoyo -t fff/the-thing` results in:

```
Exception in thread "main" java.lang.RuntimeException: Exception occurred during connect
        ...
Caused by: java.util.concurrent.ExecutionException: software.amazon.awssdk.crt.mqtt.MqttException: The connection was closed unexpectedly.
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        ...
Caused by: software.amazon.awssdk.crt.mqtt.MqttException: The connection was closed unexpectedly.
        at software.amazon.awssdk.crt.mqtt.MqttClientConnection.onConnectionComplete(MqttClientConnection.java:139)
```

**Expected behavior**
I'd expect the application to connect and send/receive messages. When I remove the line with the lastWill message and recompile it does so without issue.

**Logs/output**
CRT log shows:

```
[INFO] [2021-11-11T08:35:11Z] [000038e0] [AuthSigning] - (id=000002164E72F860) Signing successfully built canonical request for algorithm SigV4, with contents
GET
/mqtt
X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=**********%2F20211111%2Feu-west-1%2Fiotdevicegateway%2Faws4_request&X-Amz-Date=20211111T083511Z&X-Amz-SignedHeaders=host
host:*************-ats.iot.eu-west-1.amazonaws.com

host
*****************ae41e4649b934ca495991b7852b855

[INFO] [2021-11-11T08:35:11Z] [000038e0] [AuthSigning] - (id=000002164E72F860) Signing successfully built string-to-sign via algorithm SigV4, with contents
AWS4-HMAC-SHA256
20211111T083511Z
20211111/eu-west-1/iotdevicegateway/aws4_request
****************80148e8cb431021e5c4e812817a836cb299bab309

[INFO] [2021-11-11T08:35:11Z] [000038e0] [AuthSigning] - (id=000002164E72F860) Http request successfully built final authorization value via algorithm SigV4, with contents
******************c62118fcbc875108b12c78559d9b7db98952030eaefbafdffc2

[INFO] [2021-11-11T08:35:11Z] [000038e0] [thread] - id=000002164E7280D0: cpu affinity of cpu_id 0 was specified, attempting to honor the value.
[ERROR] [2021-11-11T08:35:11Z] [000038e0] [socket] - id=000002164E70C280 handle=000000000000053C: cannot write to because it is not connected
[INFO] [2021-11-11T08:35:11Z] [000038e0] [http-connection] - 000002164F1CF720: Client shutdown completed with error 0 (AWS_ERROR_SUCCESS).
[INFO] [2021-11-11T08:35:11Z] [000038e0] [connection-manager] - id=000002164E7095E0: Releasing connection (id=000002164F1CF720)
[ERROR] [2021-11-11T08:35:12Z] [000038e0] [socket] - id=000002164E726180 handle=0000000000000694: connect completion triggered with error -1073741252
[ERROR] [2021-11-11T08:35:12Z] [000038e0] [socket] - id=000002164E726180 handle=0000000000000694: connection error with code 1049
[INFO] [2021-11-11T08:35:12Z] [000038e0] [dns] - id=000002164E6D2690: recording failure for record 2a01:578:3::34d3:df62 for ***********-ats.iot.eu-west-1.amazonaws.com, moving to bad list
[INFO] [2021-11-11T08:35:12Z] [000038e0] [http-connection] - id=000002164E70C280: HTTP/1.1 client connection established.
[INFO] [2021-11-11T08:35:12Z] [000038e0] [mqtt-client] - id=000002164E7269F0: sending disconnect message as part of graceful shutdown.
[INFO] [2021-11-11T08:35:12Z] [000038e0] [http-connection] - 000002164E70C280: Client shutdown completed with error 0 (AWS_ERROR_SUCCESS).
[ERROR] [2021-11-11T08:35:12Z] [00006d8c] [mqtt-client] - id=000002164E7269F0: Connection is not open, and may not be closed
[INFO] [2021-11-11T08:35:12Z] [00006d8c] [connection-manager] - id=000002164E7095E0: release
[INFO] [2021-11-11T08:35:12Z] [00006d8c] [connection-manager] - id=000002164E7095E0: ref count now zero, starting shut down process
[INFO] [2021-11-11T08:35:12Z] [00006d8c] [connection-manager] - id=000002164E7095E0: manager release, failing 0 pending acquisitions
[INFO] [2021-11-11T08:35:12Z] [00006d8c] [connection-manager] - id=000002164E7095E0: Destroying self
[INFO] [2021-11-11T08:35:12Z] [00006d8c] [thread] - id=00000082D01FEE80: cpu affinity of cpu_id 0 was specified, attempting to honor the value.
[INFO] [2021-11-11T08:35:12Z] [00005ba4] [event-loop] - id=000002164E6CD060: Stopping event-loop thread.
```

**Comment by bretambrose** [comment]
I'm doing the exact same modification locally and not seeing any issues with connecting or publishing.  Your logs are a little brief as the actual logging where the disconnect happens has been cut out.

**Comment by bretambrose** [comment]
Followup, switching to windows, I can get this to happen.

**Comment by bretambrose** [comment]
I'm not sure if I was deluding myself yesterday or confused, but I can no longer repeat this.  Using either 0.15.8 or 0.15.9 of the CRT, I am able to establish websocket connections with a will message just fine on Windows.

If you haven't resolved this yet, I would recommend (what I was going to do until it disappeared):

* Modify the sample to make two connections, one with a will, one without
* Call connect on both
* Wait on the one that should succeed, verify it succeeded
* Wait on the one you expect to fail
* Do all this with Trace logging and then look at the two signed handshake upgrades.  Verify that the timestamp used in signing is the same (it's at seconds-level precision).  In that case the signature of each request should be the same.
* Add full (scrubbed if you want to remove credentials access key id from the logging) logs of this "twin" run here showing one succeeding and one failing.
