### ISSUE TITLE
Shadow Sample LocalValue incorrect evaluation hiding a blocking state

### ISSUE THREAD

**Issue by dcolcott** [aws/aws-iot-device-sdk-java-v2#191]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Known Issue**
- [ x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
In the Shadow example changeShadowValue(String value)  method the new Shadow value is compared to the localvalue to save publishing a Shadow update when nothing has changed. 

i.e:
        if (localValue == value) {
            System.out.println("Local value is already " + value);
            CompletableFuture<Void> result = new CompletableFuture<>();
            result.complete(null);
            return result;
        }

The problem is the value is a String and so must use localvalue.equals(value) to evaluate equality. The == method evaluates if the references are equal which of course they never are so this block of equal value and localvalue is never executed.

On its own this just means there may be a superfluous Shadow update but this method is called in the example main as such:
    gotResponse = new CompletableFuture<>();
    changeShadowValue(newValue).get();
    gotResponse.get();

Its wrapped in the CompletableFuture gotResponse. If this block is evaluated correctly with the .equals() operator and does in fact execute then a Shadow Update never occurs and the remaining logic gets stuck in a blocking state waiting for the next ShadowUpdateAccepted or ShadowUpdateRejected which never comes because the shadow wasn't updated in the first place.

**SDK version number**

**Platform/OS/Hardware/Device**
MacOS 10.15.7

**To Reproduce (observed behavior)**

1) Run the Shadow example, enter the same value a few times in a row and verify that the localvalue == value block is never executed.
2) Change the localvalue == value to correct String evaluation of localvalue.equals(value) and enter the same shadow value twice. Verify the localvalue.equals(value) is now executed but that it goes into a blocking state waiting for the ShadowUpdate response that never comes. 

**Expected behavior**
localvalue == value block evaluates correctly and logic doesn't cause a blocking state if evaluates to True.

**Logs/output**
If applicable, add logs or error output.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
-Daws.crt.debugnative=true
-Daws.crt.log.destination=File
-Daws.crt.log.level=Trace
-Daws.crt.log.filename=<path and filename>
```

**Additional context**

**Comment by jmklix** [comment]
Thanks for point this out! I've made a PR to fix the string comparison.
