### ISSUE TITLE
Alternative to onConnectionSuccess onConnectionFailure onConnectionClosed from v1 of the library 

### ISSUE THREAD

**Issue by ajb113** [aws/aws-iot-device-sdk-java-v2#203]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
MacOS

**Describe the question**
I am looking at migrating from v1 of this library. The old version exposed AWSIotMqttClient "onConnectionSuccess" "onConnectionFailure" and "onConnectionClosed" methods, which we could override to implement behaviour elsewhere. 

I know the new version of the library has MqttClientConnectionEvents onConnectionInterrupted and onConnectionResumed however these are different from success and failure. 

Is there a way to obtain notification of these events, or is this a feature request?

**Comment by jmklix** [comment]
As you mentioned adding this would need to be a feature request, so I will update this issue. As seen [here](https://github.com/awslabs/aws-crt-java/blob/main/src/main/java/software/amazon/awssdk/crt/mqtt/MqttClientConnectionEvents.java) in aws-crt-java only `onConnectionInterrupted` and `onConnectionResumed` exist.

Not sure how useful this would be in your use case, but you can watch the [lifecycle events](https://docs.aws.amazon.com/iot/latest/developerguide/life-cycle-events.html) for connected and disconnected events

**Comment by ajb113** [comment]
Thank you @jmklix, the callbacks would make it easier upgrading from v1 of the library.

In our case, we are observing onConnectionSuccess, onConnectionFailure and onConnectionClosed from the client's perspective, so lifecycle events wouldn't apply here.

**Comment by ajb113** [comment]
Hi, I was just wondering if there was an estimated time when this feature would be added?

**Comment by TwistedTwigleg** [comment]
Thanks for making this issue. We have added new callbacks to the CRT and these callbacks will be included in the next SDK release that includes the latest CRT changes - meaning it should be available soon.
Thanks again!
