### ISSUE TITLE
How to initialize StaticCredentialsProvider?

### ISSUE THREAD

**Issue by ap-northeast-0** [aws/aws-iot-device-sdk-java-v2#217]
Confirm by changing [ ] to [x] below:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
Linux

**Describe the question**
I want to establish an MQTT connection using accesskey and secretaccess key however I am getting an error. 
Below is my code:

```
DefaultAWSCredentialsProviderChain chain = new DefaultAWSCredentialsProviderChain();

CredentialsProvider credentials = new StaticCredentialsProvider
	.StaticCredentialsProviderBuilder()
	.withCredentials(new Credentials(
			chain.getCredentials().getAWSAccessKeyId().getBytes(),
			chain.getCredentials().getAWSSecretKey().getBytes(),
			null))
	.build();

MqttClientConnection mqtt = AwsIotMqttConnectionBuilder
	.newDefaultBuilder()
	.withWebsocketCredentialsProvider(credentials)
	.build();
```

This is the error:
```
ERROR 3149 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.crt.auth.credentials.StaticCredentialsProvider] with root cause

java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.crt.auth.credentials.StaticCredentialsProvider
	at software.amazon.awssdk.crt.auth.credentials.StaticCredentialsProvider$StaticCredentialsProviderBuilder.build(StaticCredentialsProvider.java:88) 
```

Hope you guys could help me.

**Comment by bretambrose** [comment]
Unless you need a credentials provider that the CRT's default chain does not have, I would use software.amazon.awssdk.crt.auth.credentials.DefaultChainCredentialsProvider rather than try and force session credentials from the regular Java SDK into a static provider in the CRT.

**Comment by jmklix** [comment]
@ap-northeast-0 is there a reason using the [AWS IoT Core Credentials Provider](https://docs.aws.amazon.com/iot/latest/developerguide/authorizing-direct-aws.html) as intended by this sdk doesn't work in your use case?

**Comment by ap-northeast-0** [comment]
@bretambrose I tried using DefaultChainCredentialsProvider but got this error. 

`nested exception is java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.crt.io.EventLoopGroup] with root cause`

```
EventLoopGroup eventLoopGroup = new EventLoopGroup(1);
HostResolver resolver = new HostResolver(eventLoopGroup);
DefaultChainCredentialsProvider defaultChain = new DefaultChainCredentialsProvider
	.DefaultChainCredentialsProviderBuilder()
	.withClientBootstrap(new ClientBootstrap(eventLoopGroup, resolver))
	.build();
```

**Comment by jmklix** [comment]
The sdk will use the DefaultChainCredentialsProvider for you if you are using websockets. You can just follow the BasicPubSub and use [websockets](https://github.com/aws/aws-iot-device-sdk-java-v2/blob/85bb4fc3864ecdbf9bc84e761bccd281ae2ca185/sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java#L549)

Or you can copy the sdk [here](https://github.com/aws/aws-iot-device-sdk-java-v2/blob/85bb4fc3864ecdbf9bc84e761bccd281ae2ca185/sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java#L549) on how to use DefaultChainCredentialsProvider
