### ISSUE TITLE
MqttClientConnectionEvents never called

### ISSUE THREAD

**Issue by j123b567** [aws/aws-iot-device-sdk-java-v2#220]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

Tried also with non ATS endpoint.

**Describe the bug**
Just `BasicPubSub` example using WebSockets. I just add `Thread.sleep(100000000);` before disconnect so it stays connected for a longer time.
After discconnecting my PC from the network, nothing happend and no "Connection interrupted: " is printed. After connecting back, also nothing happend and the application is no longer receiving messages.
According to the documentation "Connection resumed: " should be also printed when first connect is sucessful, which is also not true.

**SDK version number**
1.6.1

**Platform/OS/Hardware/Device**
Linux x86_64, Java 11, Java 8

**To Reproduce (observed behavior)**
Disconnect, wait and reconnect the network.

**Expected behavior**
Detect the network disconnect and reconnect so the callbacks can be used to e.g. subscribe again to all topics.

**Logs/output**
Before unplugging the network, just usual log lines `task-scheduler`, `socket-handler`, `websocket`, etc.
After disconnecting the network, there ware no more log messages.
After reconnecting the network after several minutes, also nothing.

**Comment by bretambrose** [comment]
The SDKs (and well, every socket-based program/library) react to socket closed notifications from the OS.  In the absence of them, nothing will happen.  If you have evidence that the socket is being torn down and the SDK is not reacting as it should, we'd be interested in seeing it.

In your situation, there are two primary possibilities that will trigger a disconnect:
1. One side closes the socket on their side of the connection (sending a FIN to the other side), kicking off the TCP close process.
1. A keep alive timeout is triggered -- for example,  TCP keep alive or MQTT keep alive.  Both of these are configurable within the SDK: 
* * https://github.com/awslabs/aws-crt-java/blob/main/src/main/java/software/amazon/awssdk/crt/io/SocketOptions.java#L84
* * https://github.com/awslabs/aws-crt-java/blob/main/src/main/java/software/amazon/awssdk/crt/mqtt/MqttConnectionConfig.java#L210

There are some more, less common, situations that aren't really relevant to your situation (RST receipt for example).

In your example, disconnecting from the network isn't going to trigger anything locally on the client, but (pure speculation here), reconnecting to the network will likely reset some sort of network state that breaks the original circuit from a routing perspective leading to a dead connection until a timeout is triggered.  In this case, lowering one of those timeouts to something that works well for you is probably your best approach.
