### ISSUE TITLE
At regular interval getting Connection interrupted call back - "Connection interrupted: 46 : System call failure"

### ISSUE THREAD

**Issue by agupta0105** [aws/aws-iot-device-sdk-java-v2#222]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?

**Describe the question**
I have written simple pub sub client quite similar to what is there in the sample but when deployed on ec2 k8 instance, getting connection interrupt as "Connection interrupted: 46 : System call failure" at regular interval of 20 mins. I am using version 1.6.1 of aws-iot-device-sdk-java-v2. If I run the same command in my laptop, I dont see this issue. Could someone shed light on what could cause this issue and what exactly is that error code signifies.

**Comment by jmklix** [comment]
It could possibly be something affected by the pingTimeoutMs. Can you attach logs from when this is happening to you.

Enable logging with the following:
```
-Daws.crt.debugnative=true
-Daws.crt.log.destination=File
-Daws.crt.log.level=Trace
-Daws.crt.log.filename=<path and filename>
```

**Comment by agupta0105** [comment]
I enabled it last night and just now did some testing and attached are the logs. Interestingly I could see in the logs "[socket] - id=0x7f471410cdc0 fd=27: closed remotely" After a gap of inactivity on the socket.

Is there something where client needs to send some HB periodically to the broker to keep the connection alive.
[aws-1.log](https://github.com/aws/aws-iot-device-sdk-java-v2/files/8139320/aws-1.log)

**Comment by agupta0105** [comment]
Also even after setting up keepAliveSecs to 120 or 1300, I could not see any diff in the logs. After every 20 mins, ping req is created but could not be sent due to connection closed by peer.

**Comment by agupta0105** [comment]
I have solved this issue but curios to know that why sdk itself was not sending HB to keep the session alive. If ping is for the same purpose then why setting pingTimeout was not working as expected. Ping req was always sent after 20 mins . Please fix this
