### ISSUE TITLE
Default Custom Authorizer invalid TLS ALPN

### ISSUE THREAD

**Issue by TheNodi** [aws/aws-iot-device-sdk-java-v2#267]
### Describe the bug

The SDK is checking for `x-amz-customauthorizer-name` string inside the username to override the TLS ALPN list and use custom authorizers:
https://github.com/aws/aws-iot-device-sdk-java-v2/blob/c04ce42a7c83bb6aa5f8e51b2cd1af44f99fc7d1/sdk/src/main/java/software/amazon/awssdk/iot/AwsIotMqttConnectionBuilder.java#L521-L524

When specifing a custom domain with a default custom authorizer (see [Creating and configuring custom domains](https://docs.aws.amazon.com/iot/latest/developerguide/iot-custom-endpoints-configurable-custom.html), `x-amz-customauthorizer-name` parameter is not required. If override is disabled, specifing the parameter may result in an error.

### Expected Behavior

I can connect to a custom domain using the default authrizer, without specifing `x-amz-customauthorizer-name` parameter.

### Current Behavior

Skipping `x-amz-customauthorizer-name` parameter does not set the correct TLS ALPN.

### Reproduction Steps

- Create a custom authorizer.
- Create a domain that uses the authorizer as default, without override.
- Attempt to connect to the custom domain without specifing the authorizer name.
- Connection fails with `software.amazon.awssdk.crt.mqtt.MqttException: TLS (SSL) negotiation failed`

Example code:
```kotlin
AwsIotMqttConnectionBuilder
    .newDefaultBuilder()
    .withCertificateAuthority(
        // AmazonRootCA1.pem
    )
    .withEndpoint("mqtt.example.com")
    .withPort(443)
    .withBootstrap(cb)
    .withClientId("hello-world")
    .withUsername(
        "username" +
                "?x-amz-customauthorizer-signature=......" +
                "&token=....."
    )
    .build()
```

### Possible Solution

I don't see a query parameter required in all situations for custom authorizer to use as an implicit flag.
Name is optional in default authorizers. Signature can be disabled.
Probably an explicit building method is required.

### Additional Information/Context

I've been working around this issue by appending `&workaround=x-amz-customauthorizer-name` query parameter to trigger the builder condition.

### SDK version used

1.8.4

### Environment details (OS name and version, etc.)

Fedora 34, Kotlin 1.6.20, Java 11

**Comment by TwistedTwigleg** [comment]
Thank you making this issue! I will look into this 👍
