### ISSUE TITLE
Greengrass IPC read port

### ISSUE THREAD

**Issue by bgklika** [aws/aws-iot-device-sdk-java-v2#279]
### Describe the feature

For greengrass IPC  we need to have ability to read actual value of port where service has been bound.

### Use Case

It will usefil to configure port to value 0 which means will be selected later by OS when bind() is called.

### Proposed Solution

I suppose to [update aws-crt-java first](https://github.com/awslabs/aws-crt-java/pull/489). After that we can read actual value of port in aws-iot-device-sdk-java-v2.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

main

### Environment details (OS name and version, etc.)

any

**Comment by graebm** [comment]
I'm working on this...

**Comment by graebm** [comment]
Resolved in v1.9.0
