### ISSUE TITLE
AwsIotMqtt5ClientBuilder always creates AwsIotMqtt5ClientBuilder with port: 8883 

### ISSUE THREAD

**Issue by dimsh7** [aws/aws-iot-device-sdk-java-v2#345]
### Describe the feature

Hi.
In previous version was available to define port for AwsIotMqttConnectionBuilder
For example builder.withPort((short) Integer.parseInt(getCommandOrDefault("port", "443")) ).
AwsIotMqtt5ClientBuilder always use port 8883 for direct connect.

### Use Case

There are a lot of cases that the port 8443 is blocked by a firewall/organization policy. 
I would like to use common permitted 443 port.

### Proposed Solution

To give an option to define used port number.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

v1.11.0

### Environment details (OS name and version, etc.)

Windows 10 , use  aws-iot-device-sdk-java-v2

**Comment by TwistedTwigleg** [comment]
Thank you for opening this issue!

By default, the MQTT5 builder will use port `8883` for a direct MQTT connection and `443` for websockets, but you can override this with the [withPort](https://aws.github.io/aws-iot-device-sdk-java-v2/software/amazon/awssdk/iot/AwsIotMqtt5ClientBuilder.html#withPort(java.lang.Long)) function in the MQTT5 builder, just like in the MQTT311 builder. You should be able to do `builder.withPort(443L)` and then it will use port `443` even if your builder was initially created for a direct MQTT connection.

**Comment by dimsh7** [comment]
Thanks!
