### ISSUE TITLE
Android binaries of the library haven't published

### ISSUE THREAD

**Issue by bgklika** [aws/aws-iot-device-sdk-java-v2#346]
### Describe the feature

AWS IoT Device SDK for Java v2 has  build on Android via gradle in https://github.com/aws/aws-iot-device-sdk-java-v2/tree/main/android. 

But in different with CRT Android binaries (AAR) and POM files of  Iot device SDK  haven't publically available. 
I searching on https://aws.oss.sonatype.org/content/repositories/snapshots/ ,  https://aws.oss.sonatype.org/ and also maven central but did not found packages with artifactId aws-iot-device-sdk-android.

Unfortunately is not  possible to build project with non-Android build of SDK even when it does not contains any Android specific code just because or references another Android-specific CRT package.

Currently we need a slightly outdated version 1.10.3 of SDK 
Please build and publish v1.10.3 of the SDK for Android. 
In the best case Android artifacts build and publishing need to be added to CI pipelines.

### Use Case

Use IoT Device SDK for project for Android  OS.

### Proposed Solution

Temporary - build and publish Android  artifacts manually for version 1.10.3. 
Permanent - build and publish Android  artifacts together with release procedures as for default build.

### Other Information

Unfortunatly I have no permissions to publish on maven central or sonatype.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

1.10.3

### Environment details (OS name and version, etc.)

Android

**Comment by MikeDombo** [comment]
https://mvnrepository.com/artifact/software.amazon.awssdk.crt/aws-crt-android

Replace the dependency with aws-crt-android.

**Comment by bgklika** [comment]
We already did it  in aws-iot-device-sdk-android uploaded to private maven repo. There is no public aws-iot-device-sdk-android. aws-iot-device-sdk dependent on aws-crt which is not situable for Android.

**Comment by MikeDombo** [comment]
You can use dependency exclusions to remove the dependency on aws-crt and add the proper dependency on aws-crt-android. There is no aws-iot-device-sdk-android.

**Comment by bgklika** [comment]
Will try to that. In any case better publish official build.

**Comment by jmklix** [comment]
This is something that is on our roadmap, but I don't have a set date for when it will be completed

**Comment by bretambrose** [comment]
Closing older Android issues; Android became officially supported late in 2023.  If you continue encounter problems, please create a new issue.
