### ISSUE TITLE
Setting SNI for Enhanced Custom Authentication

### ISSUE THREAD

**Issue by aloysiustany** [aws/aws-iot-device-sdk-java-v2#35]
Hi,

I am trying to use the AWS IoT Java SDK v2 to build a device and connect to AWS IoT. We use enhanced custom authentication to authenticate the devices. I don't see an option to send the SNI TLS extension through this SDK. How do I do it ?

> Devices that use enhanced custom authentication must send the Server Name Indication (SNI) TLS extension with a value that matches the domain of the appropriate domain configuration. 

source: https://docs.amazonaws.cn/en_us/iot/latest/developerguide/enhanced-custom-auth-using.html

**Comment by JonathanHenson** [comment]
Set server name on TlsConnectionOptions.

But it looks like we didn’t bind that out so it’s currently set to the endpoint dns name. SNI is always used. Do you want to set it to something other than the endpoint? If so, we can expose the api to do so.
