### ISSUE TITLE
Exception: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Devoamos** [aws/aws-iot-device-sdk-java-v2#363]
### Describe the bug

My team is following the sample basic connect/pub-sub code samples provided by the SDK samples to create a connection in order to migrate from SDK v1 -> v2 and continue publishing messages. 

Previous version 1.3.9 

```
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-iot-device-sdk-java</artifactId>
    <version>1.3.9</version>
 </dependency>
```
 

V2 version 1.11.0

```
<dependency>
  <groupId>software.amazon.awssdk.iotdevicesdk</groupId>
  <artifactId>aws-iot-device-sdk</artifactId>
  <version>1.11.0</version>
</dependency>
```

We have decided to go with the **.newMtlsBuilderFromPath()** option but can see the below error on startup.

{"time":"2023-01-16T09:50:05.086Z","level":"INFO","thread":"main","method":"logMessage","msg":"__Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.","logger":"ConditionEvaluationReportLoggingListener","exception":"","logger_name":"org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener"} {"time":"2023-01-16T09:50:05.299Z","level":"ERROR","thread":"main","method":"reportFailure","msg":"Application run failed","logger":"SpringApplication","exception":"org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'messagePublisher' defined in URL [jar:file:/app/app.jar!/BOOT-INF/classes!/uk/co/argos/convenience/ccutils/iot/MessagePublisher.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [.MessagePublisher]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /tmp/AWSCRT_3245581712843744318libaws-crt-jni.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/AWSCRT_3245581712843744318libaws-crt-jni.so)\n\tat org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)\n\tat org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296)\nCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [iot.MessagePublisher]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /tmp/AWSCRT_3245581712843744318libaws-crt-jni.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/AWSCRT_3245581712843744318libaws-crt-jni.so)\n\tat org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)\n\tat org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)\nCaused by: java.lang.UnsatisfiedLinkError: /tmp/AWSCRT_3245581712843744318libaws-crt-jni.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/AWSCRT_3245581712843744318libaws-crt-jni.so)\n\tat java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)\n\tat java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)\n","logger_name":"org.springframework.boot.SpringApplication"}

Can anyone assist with the root cause?

### Expected Behavior

The application starts in the docker container and can publish IOT messages. 

### Current Behavior

The following exception is logged after the container is killed during startup 

`{"time":"2023-01-16T09:50:05.086Z","level":"INFO","thread":"main","method":"logMessage","msg":"__Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.","logger":"ConditionEvaluationReportLoggingListener","exception":"","logger_name":"org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener"} {"time":"2023-01-16T09:50:05.299Z","level":"ERROR","thread":"main","method":"reportFailure","msg":"Application run failed","logger":"SpringApplication","exception":"org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'messagePublisher' defined in URL [jar:file:/app/app.jar!/BOOT-INF/classes!/uk/co/argos/convenience/ccutils/iot/MessagePublisher.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [uk.MessagePublisher]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /tmp/AWSCRT_3245581712843744318libaws-crt-jni.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/AWSCRT_3245581712843744318libaws-crt-jni.so)\n\tat org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)\n\tat org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296)\nCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [uk.MessagePublisher]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /tmp/AWSCRT_3245581712843744318libaws-crt-jni.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/AWSCRT_3245581712843744318libaws-crt-jni.so)\n\tat org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)\n\tat org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)\nCaused by: java.lang.UnsatisfiedLinkError: /tmp/AWSCRT_3245581712843744318libaws-crt-jni.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/AWSCRT_3245581712843744318libaws-crt-jni.so)\n\tat java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)\n\tat java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)\n","logger_name":"org.springframework.boot.SpringApplication"}`

### Reproduction Steps

Use [basic/pub sample](https://github.com/aws/aws-iot-device-sdk-java-v2/blob/main/samples/BasicPubSub/src/main/java/pubsub/PubSub.java) in a Spring application 
Spring - V2.7.x+ 
Java11
And run in a 
Docker container - Alpine Linux OS

### Possible Solution

It has been suggested in multiple threads [1] to install the gcompat library but errors are still occurring on startup. 

[1] https://stackoverflow.com/questions/50288034/unsatisfiedlinkerror-tmp-snappy-1-1-4-libsnappyjava-so-error-loading-shared-li 

### Additional Information/Context

Happy to provide anymore information that can help.

### SDK version used

1.11.0

### Environment details (OS name and version, etc.)

Alpine Linux 3.15

**Comment by bretambrose** [comment]
The CRT dependency does not yet support alpine (in particular, musl) within maven packaging.  You can build it yourself on an alpine system and it should work but then you'll have to copy jars around.  Musl support was put on hold recently due to shifting prioritizations.

**Comment by jmklix** [comment]
Changing this to a feature request for Alpine Linux. As @bretambrose stated this is something that we have planned.

**Comment by Devoamos** [comment]
Thanks for the response! 

@bretambrose - We may attempt that suggestion as a workaround. 

`"You can build it yourself on an alpine system and it should work but then you'll have to copy jars around"`
For my knowledge, what's the best way to approach the above?

**Comment by Devoamos** [comment]
@jmklix / @bretambrose - What are the general next steps for an issue like this?

**Comment by jmklix** [comment]
You will need to wait for us to add official support for this to work. The other option is to
> build it yourself on an alpine system and it should work but then you'll have to copy jars around

**Comment by bretambrose** [comment]
I believe this was addressed with a CRT release in the middle of last year: https://github.com/awslabs/aws-crt-java/releases/tag/v0.23.0
