### ISSUE TITLE
[MQTT5] "Could not connect: socket is closed" Exception when using X.509 certs. 

### ISSUE THREAD

**Issue by Suzuhana** [aws/aws-iot-device-sdk-java-v2#370]
### Describe the bug

Hi, I created a set of certs which works using old mqtt3 `AwsIotMqttConnectionBuilder.newMtlsBuilder` (supplied with endpoint, device cert, private key and rootCA)

but when I try to run mqtt5 sample (I slightly modified it to use in-memory certs) with **same** set of certs and endpoint, it gives `Could not connect: socket is closed when it connects`. 

(I did the test side by side, no any changes on the policy and thing configuration).

I tested in both android and MacOS

Below is code snippet I used to build client
```java
            String certificate = "[expression to read cert]";
            String privateKey = "[expression to read privateKey]";
            String caRoot = "[expression to read caRoot]";
            
            AwsIotMqtt5ClientBuilder builder = AwsIotMqtt5ClientBuilder.newDirectMqttBuilderWithMtlsFromMemory(
                    "[prefix].iot.us-east-1.amazonaws.com", certificate, privateKey);

            builder.withCertificateAuthority(caRoot);

            ConnectPacket.ConnectPacketBuilder connectProperties = new ConnectPacket.ConnectPacketBuilder();
            connectProperties.withClientId("test-" + UUID.randomUUID().toString());

            builder.withConnectProperties(connectProperties);

            builder.withLifeCycleEvents(lifecycleEvents);
            builder.withPublishEvents(publishEvents);

            Mqtt5Client returnClient = builder.build();
            builder.close();
```

Policy I used for test:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "*"
    }
  ]
}
```

### Expected Behavior

It should connect successfully like mqtt3

### Current Behavior

it gives `java.lang.Exception: Could not connect: socket is closed.` when below codes are called.

```java
            /* Connect */
            client.start();
            try {
                lifecycleEvents.connectedFuture.get(60, TimeUnit.SECONDS);
            } catch (Exception ex) {
                throw new RuntimeException("Exception occurred during connect", ex);
            }
```

### Reproduction Steps

Check "Describe the bug" section.

### Additional Information/Context

I tested sigv4 websocket connection which seems to be totally fine.

### SDK version used

1.11.4   and aws-crt-android/aws-crt 0.21.7

### Environment details (OS name and version, etc.)

Android and MacOS

**Comment by Suzuhana** [comment]
Maybe it's irrelevant. I tested mqtt5 version of websocket mqtt, which works fine.

**Comment by bretambrose** [comment]
Can you attach CRT debug logging of an attempt that failed?

**Comment by Suzuhana** [comment]
@bretambrose  Could you suggest a way to enable debug logging of CRT?

**Comment by Suzuhana** [comment]
Nvm, I figured out:
```
Caused by: java.util.concurrent.ExecutionException: java.lang.Exception: Could not connect: socket is closed.
    at java.util.concurrent.CompletableFuture.reportGet (CompletableFuture.java:396)
    at java.util.concurrent.CompletableFuture.get (CompletableFuture.java:2096)
    at mqtt5.pubsub.PubSub.main (PubSub.java:172)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:293)
    at java.lang.Thread.run (Thread.java:833)
Caused by: java.lang.Exception: Could not connect: socket is closed.
    at mqtt5.pubsub.PubSub$SampleLifecycleEvents.onConnectionFailure (PubSub.java:94)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[DEBUG] [2023-02-10T15:44:42Z] [000000016f033000] [task-scheduler] - id=0x14764c510: Running Mqtt5Service task with <Running> status
[DEBUG] [2023-02-10T15:44:42Z] [000000016f033000] [mqtt5-client] - id=0x14764c4e0: switching current state from PENDING_RECONNECT to CONNECTING
[INFO] [2023-02-10T15:44:42Z] [000000016f033000] [mqtt5-client] - id=0x14764c4e0: emitting connecting lifecycle event
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolving host aqus7jhq4fkh9-ats.iot.us-east-1.amazonaws.com
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 3.228.133.233
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 100.26.71.252
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 54.208.54.145
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 54.85.146.9
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 52.86.55.159
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 52.0.71.112
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 34.233.203.183
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 3.223.166.80
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 2406:da00:ff00::2ccf:5a1a
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 2406:da00:ff00::12d1:52d8
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 2406:da00:ff00::3d1:a980
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 2406:da00:ff00::36ad:775c
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 2406:da00:ff00::369c:16b8
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 2406:da00:ff00::3448:605c
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 2406:da00:ff00::3406:b315
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static: resolved record: 2406:da00:ff00::2cc1:f72b
[DEBUG] [2023-02-10T15:44:43Z] [000000016f2ef000] [dns] - static, resolving host aqus7jhq4fkh9-ats.iot.us-east-1.amazonaws.com successful, returned 16 addresses
[WARN] [2023-02-10T15:44:43Z] [000000016bfbf000] [JavaCrtGeneral] - Not all native threads were successfully joined during gentle shutdown.  Memory may be leaked.

```

**Comment by bretambrose** [comment]
Hmm, that is not a useful log (not your fault, it just has no indication of what's going on).

Can you try a few other things:

(1) Bump the log level up to trace.  Most of the tls logging on Macs is trace level.
(2) Get logs for both mac and android/linux.  

Attach the logs as files since they'll be too big to just paste into a text box.

**Comment by Suzuhana** [comment]
[trace_logs_mac_java.txt](https://github.com/aws/aws-iot-device-sdk-java-v2/files/10711672/trace_logs_mac_java.txt)

[trace_logs_android.txt](https://github.com/aws/aws-iot-device-sdk-java-v2/files/10711768/trace_logs_android.txt)

@bretambrose  Check above logs.

**Comment by bretambrose** [comment]
Iot Core is hanging up on you after receiving the initial ClientHello part of the TLS handshake.

**Comment by Suzuhana** [comment]
The key and cert I acquired from the  `AWS Iot -> Security -> Certificates -> Add Certificate -> Create certificate -> Auto-generate new certificate`. Do you think anything else needs to be done?  Since same cert and key is working in `AwsIotMqttConnectionBuilder.newMtlsBuilder`, is the process of hitting IoT service is different in Mqtt5?

**Comment by bretambrose** [comment]
The differences between 5 and 3 do not come into play until much later in the connection process after the tls handshake has completed successfully.  You mentioned something about making a change to use cert/key from in-memory.  What change did you make?

**Comment by Suzuhana** [comment]
@bretambrose 

```Java
            String certificate = "[expression to read cert]";
            String privateKey = "[expression to read privateKey]";
            String caRoot = "[expression to read caRoot]";
            
            **AwsIotMqtt5ClientBuilder builder = AwsIotMqtt5ClientBuilder.newDirectMqttBuilderWithMtlsFromMemory(
                    "[prefix].iot.us-east-1.amazonaws.com", certificate, privateKey);

            builder.withCertificateAuthority(caRoot);**

            ConnectPacket.ConnectPacketBuilder connectProperties = new ConnectPacket.ConnectPacketBuilder();
            connectProperties.withClientId("test-" + UUID.randomUUID().toString());

            builder.withConnectProperties(connectProperties);

            builder.withLifeCycleEvents(lifecycleEvents);
            builder.withPublishEvents(publishEvents);

            Mqtt5Client returnClient = builder.build();
            builder.close();
```
Instead of reading from path, reading the certs beforehand then pass strings to the `newDirectMqttBuilderWithMtlsFromMemory`

**Comment by bretambrose** [comment]
What happens if you just use the API that reads from the materials from files (on the mac, for example)?

**Comment by Suzuhana** [comment]
Let me try that.

**Comment by Suzuhana** [comment]
Seems to be the same error. 

And btw I tried to use below command from {https://github.com/aws/aws-iot-device-sdk-java-v2/tree/main/samples#mqtt5-pubsub} with no local changes on my end (besides only one logging statement). 

`mvn compile exec:java -pl samples/Mqtt5/PubSub -Dexec.mainClass=mqtt5.pubsub.PubSub -Dexec.args='--endpoint <endpoint> --cert <path to certificate> --key <path to private key> --ca_file <path to root CA>'`

It throws `software.amazon.awssdk.crt.CrtRuntimeException: aws_tls_ctx_options_init_client_mtls_from_path failed (aws_last_error: AWS_ERROR_FILE_INVALID_PATH(44), Invalid file path.) AWS_ERROR_FILE_INVALID_PATH(44)`

Seems like in sample codes neither `withCertificateAuthority` nor `withCertificateAuthorityFromPath` are invoked to consume --ca_file parameter.

**Comment by bretambrose** [comment]
The sample ignores the ca file parameter but you shouldn't need it on Macs, where AmazonRootCA1.pem is already in the system trust store.  Android is different because they don't include it.

**Comment by Suzuhana** [comment]
@bretambrose  the Invalid file path was a mistake on my end.
For the issue itself, I think I figured out the issue:  default port is set to `8883`. which may not be open over company's network (I should not assume the port is opened in the first place). When I specify port # to `443`, it works.  Now I have another thing want to confirm. Does AWS IoT Core open 443 for direct mqtt connection?

**Comment by bretambrose** [comment]
443 works assuming alpn is supported on the platform (not supported on Windows <= 8.0, everything else is fine)

**Comment by Suzuhana** [comment]
Thanks for the help!
