### ISSUE TITLE
The latest release does not include commit b138173bde9c8a644e84de3c08e0e46fe4a3f186

### ISSUE THREAD

**Issue by JacCas2014** [aws/aws-iot-device-sdk-java-v2#382]
### Describe the bug

I've tried using 1.11.5 from maven (https://mvnrepository.com/artifact/software.amazon.awssdk.iotdevicesdk/aws-iot-device-sdk) and am unable to see the code changes made by commit: https://github.com/aws/aws-iot-device-sdk-java-v2/commit/b138173bde9c8a644e84de3c08e0e46fe4a3f186. Has it somehow not been tagged or is the tagged version in maven incorrect?

### Expected Behavior

I expected to have access to the documented code from the  commit https://github.com/aws/aws-iot-device-sdk-java-v2/commit/b138173bde9c8a644e84de3c08e0e46fe4a3f186 in release 1.11.5, but I'm unable to resolve the code.

### Current Behavior

It's the version of the code prior to this commit that's in 1.11.5.

### Reproduction Steps

Use 1.11.5 from maven then try to find the code in commit https://github.com/aws/aws-iot-device-sdk-java-v2/commit/b138173bde9c8a644e84de3c08e0e46fe4a3f186.

### SDK version used

1.8

### Environment details (OS name and version, etc.)

IntelliJ IDEA 2021.1.3 (Community Edition)

**Comment by JacCas2014** [comment]
Thanks. Closing this.

**Comment by TwistedTwigleg** [comment]
Thanks for bringing this up. Our documentation used to be generated on every merge, so it would reflect the current status of `main` rather than the latest release. We have adjusted this so it will update only on releases, so it properly reflects the status of the last release.

Thanks again!
