### ISSUE TITLE
Android app crash in release mode

### ISSUE THREAD

**Issue by ngbahiep** [aws/aws-iot-device-sdk-java-v2#443]
### Describe the bug

Hi, 
I am using this sdk to connect to aws mqtt. everything works fine in debug mode. However, app crash in release mode.
I do some testing and found that if I set minifyEnabled and shrinkResources to false, it works. Otherwise, it does not. 
Below is the error:
`#01 pc 001c3d97  /data/app/com.xxx.xxx-zJ8Km5JEAhZ5OvpxzwJOMQ==/lib/arm/libaws-crt-jni.so (aws_fatal_assert+50)'

'#02 pc 000525e3  /data/app/com.xxx.xxx-zJ8Km5JEAhZ5OvpxzwJOMQ==/lib/arm/libaws-crt-jni.so (cache_java_class_ids+17026)'

'#03 pc 000490ab  /data/app/com.xxx.xxx-zJ8Km5JEAhZ5OvpxzwJOMQ==/lib/arm/libaws-crt-jni.so (Java_software_amazon_awssdk_crt_CRT_awsCrtInit+258)'

'#04 pc 0003677b  /data/app/com.xxx.xxx-zJ8Km5JEAhZ5OvpxzwJOMQ==/oat/arm/base.odex (offset 0x34000)`

### Expected Behavior

I expect app should work

### Current Behavior

current is app crash

### Reproduction Steps

It crashes when start connect to mqtt

### SDK version used

v1.14.0

### Environment details (OS name and version, etc.)

android

**Comment by bretambrose** [comment]
Android isn't officially supported yet.  I'll bring this up with the engineer working on it though.

**Comment by bretambrose** [comment]
I should have added to the original response: minify/shrink will absolutely not work under any circumstances until (unless) we add support to essentially skip the entire common runtime from the tree-shaking.  The native part of the common runtime uses JNI references to classes and minify/shrink will throw those methods/classes away because it doesn't understand usage external to Java.

**Comment by ngbahiep** [comment]
thank you @bretambrose . I excluded aws iot sdk in proguard file. my android app works now.

**Comment by jleskovar-tyro** [comment]
For future Android travellers - the following proguard declarations should be enough to prevent the crash
```
-keepclasseswithmembernames class * {
    native <methods>;
}

-keep class software.amazon.awssdk.crt.** { *; }
-keep class software.amazon.awssdk.iot.** { *; }
```
