### ISSUE TITLE
After a reconnect with a clean session, subscription stops working

### ISSUE THREAD

**Issue by rafaturtle** [aws/aws-iot-device-sdk-java-v2#452]
### Describe the bug

Hi
I connect with clean session false to pick up any offline messages but if I keep the device offline for a long time, I can see that the connection resumes but after subscribing to the same topic I no longer receive any messages. No logs, no errors, nothing. I'm not exactly sure how to go about debugging this. Any advice?

### Expected Behavior

After reconnecting and subscribing, I should go back to receiving messages. 

### Current Behavior

No message received after long time offline 

### Reproduction Steps

Connect to the broker using clean session false and a time to live. Connect but then lock your firewall to force disconnection. If you reconnect quickly things goes back to normal but if you take a long time, hours, than even after subscribing again to the topic I get no messages. 

### SDK version used

1.11.2

### Environment details (OS name and version, etc.)

Running on windows 11

**Comment by jmklix** [comment]
What happens when you don't use a clean session in the same scenario? Are you using MQTT3 or MQTT5? What sample are you using to reproduce this?

**Comment by xiazhvera** [comment]
The persistent session expires after a certain time period. The default expire time for AWS IoT is 3600 seconds = 1hour. If you are offline for 1 hour, it is likely the session is expired. 
Checkout the limit here: https://docs.aws.amazon.com/general/latest/gr/iot-core.html#message-broker-limits

**Comment by rafaturtle** [comment]
I've figured out what was going on and perhaps it's not a bug. When publishing messages whilst offline I was ending with .get(). I also had a .get() during topic subscription 
This would cause it to resume connection but not receive any more message. 
Thanks for the suggestions
