### ISSUE TITLE
Old requests from the previous session are cancelled, and offline request will not be accept.

### ISSUE THREAD

**Issue by phuongnh-1588** [aws/aws-iot-device-sdk-java-v2#458]
### Describe the issue

The error occurs after subscribing to receive a list of jobs, but upon encountering the error message, I'm unsure how to fix it. Please help me understand how to resolve this issue. The error message is: "Old requests from the previous session are canceled, and offline requests will not be accepted."

Here are the steps leading up to the error:

1. I establish a connection and register a Thing from the client.
2. I then reconnect using a permanentCertificate and permanentPrivateKey.
3. Next, I attempt to use the `subscribeJobNotify` method to retrieve a list of jobs associated with the registered Thing's name.

However, I encounter an error message that states: "Old requests from the previous session are canceled, and offline requests will not be accepted."

Could you provide assistance in resolving this issue? Additionally, here is the code snippet for the `subscribeJobNotify` method: 

```
    fun subscribeJobNotify(thingNameKitting: String): JobExecutionsChangedEvent? {
        if (connection == null || !isConnected) return null
        LogUtils.logE("--------------start subscribeJobNotify ------------")
        val iotJobsClient =  IotJobsClient(connection)
        var jobChangeEvent: JobExecutionsChangedEvent? = null
        val gotResponse = CompletableFuture<Boolean?>()
        val requestJobExecutionsChangedSubscription = JobExecutionsChangedSubscriptionRequest()
        requestJobExecutionsChangedSubscription.thingName = thingNameKitting

        val subscribeToJobExecutionsChangedEvents  =  iotJobsClient.SubscribeToJobExecutionsChangedEvents(
            requestJobExecutionsChangedSubscription,
            QualityOfService.AT_LEAST_ONCE,

            ) {
            LogUtils.logE(" get subscribeToJobExecutionsChangedEvents completed: ${it.jobs}")
            jobChangeEvent = it
            gotResponse?.complete(null)
        }
        try {
            subscribeToJobExecutionsChangedEvents.get()
        } catch (e: Exception) {
            LogUtils.logE(" get subscribeToJobExecutionsChangedEvents error :${e.message} ")
        }
        return jobChangeEvent
    }
```

### Links

[N/A](https://docs.aws.amazon.com/iot/latest/developerguide/jobs-devices.html)

**Comment by phuongnh-1588** [comment]
> ### Describe the issue
> The error occurs after subscribing to receive a list of jobs, but upon encountering the error message, I'm unsure how to fix it. Please help me understand how to resolve this issue. The error message is: "Old requests from the previous session are canceled, and offline requests will not be accepted."
> 
> Here are the steps leading up to the error:
> 
> 1. I establish a connection and register a Thing from the client.
> 2. I then reconnect using a permanentCertificate and permanentPrivateKey.
> 3. Next, I attempt to use the `subscribeJobNotify` method to retrieve a list of jobs associated with the registered Thing's name.
> 
> However, I encounter an error message that states: "Old requests from the previous session are canceled, and offline requests will not be accepted."
> 
> Could you provide assistance in resolving this issue? Additionally, here is the code snippet for the `subscribeJobNotify` method:
> 
> ```
>     fun subscribeJobNotify(thingNameKitting: String): JobExecutionsChangedEvent? {
>         if (connection == null || !isConnected) return null
>         LogUtils.logE("--------------start subscribeJobNotify ------------")
>         val iotJobsClient =  IotJobsClient(connection)
>         var jobChangeEvent: JobExecutionsChangedEvent? = null
>         val gotResponse = CompletableFuture<Boolean?>()
>         val requestJobExecutionsChangedSubscription = JobExecutionsChangedSubscriptionRequest()
>         requestJobExecutionsChangedSubscription.thingName = thingNameKitting
> 
>         val subscribeToJobExecutionsChangedEvents  =  iotJobsClient.SubscribeToJobExecutionsChangedEvents(
>             requestJobExecutionsChangedSubscription,
>             QualityOfService.AT_LEAST_ONCE,
> 
>             ) {
>             LogUtils.logE(" get subscribeToJobExecutionsChangedEvents completed: ${it.jobs}")
>             jobChangeEvent = it
>             gotResponse?.complete(null)
>         }
>         try {
>             subscribeToJobExecutionsChangedEvents.get()
>         } catch (e: Exception) {
>             LogUtils.logE(" get subscribeToJobExecutionsChangedEvents error :${e.message} ")
>         }
>         return jobChangeEvent
>     }
> ```
> 
> ### Links
> [Document  Jobs](https://docs.aws.amazon.com/iot/latest/developerguide/jobs-devices.html)

**Comment by yasminetalby** [comment]
Hello @phuongnh-1588,

Thank you very much for your submission.

Could you please provide the following information:
- SDK version number
- Environment details (OS name and version, etc.)
- Trace log
-  Device policy

Thank you very much for your time and collaboration.

Sincerely,

Yasmine
