### ISSUE TITLE
Problem not finding AWS CRT lib in Windows development environment.

### ISSUE THREAD

**Issue by arcjjang** [aws/aws-iot-device-sdk-java-v2#46]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
※ My Development environment
- OS : Windows 10
- JAVA : Amazon Corretto 11
- Spring Boot v2 with gradle
- aws-iot-device-sdk v1.0.5

**Describe the question**

There was no problem until version 1.0.1, but the following error occurs in version 1.0.5.

`Unable to unpack AWS CRT lib: java.io.IOException: Unable to open library in jar for AWS CRT: /windows/x86_64/aws-crt-jni.dll
java.io.IOException: Unable to open library in jar for AWS CRT: /windows/x86_64/aws-crt-jni.dll
	at software.amazon.awssdk.crt.CRT.loadLibraryFromJar(CRT.java:132)
	at software.amazon.awssdk.crt.CRT.<clinit>(CRT.java:38)
        at software.amazon.awssdk.crt.CrtResource.<clinit>(CrtResource.java:99)`

Please let me know if I missed anything.

Thank you in advance.

**Comment by bretambrose** [comment]
Are you building everything yourself or are you pulling the CRT/SDK from maven?

**Comment by arcjjang** [comment]
I am pulling the CRT/SDK from gradle.
`// https://mvnrepository.com/artifact/software.amazon.awssdk.iotdevicesdk/aws-iot-device-sdk
compile group: 'software.amazon.awssdk.iotdevicesdk', name: 'aws-iot-device-sdk', version: '1.0.5'`

**Comment by bretambrose** [comment]
Just verified that you're correct.  Our CI pipeline has been under development to support a lot of new platforms and something must have broken, as the only windows build in the crt jar is x86_32.  Clearly we also need a "pull and run a sample" step for each platform post-publish.  We'll try and get a fixed version of the crt and v2 sdk out by Monday at the latest.

**Comment by bretambrose** [comment]
1.0.6 is now in maven central and contains both 32 and 64 bit builds for Windows.

**Comment by arcjjang** [comment]
I succeeded in build in version 1.0.6. Thank you.
