### ISSUE TITLE
latest android sample broken

### ISSUE THREAD

**Issue by minghuadev** [aws/aws-iot-device-sdk-java-v2#480]
### Describe the bug

Two issues: 

[1] https://github.com/aws/aws-iot-device-sdk-java-v2/blob/main/samples/Android/app/build.gradle#L39
these 4 lines, are missing a slash "/" after the second ../.. thus causing a class loader failure. 

[2] https://github.com/aws/aws-iot-device-sdk-java-v2/blob/main/samples/Android/app/src/main/java/software/amazon/awssdk/iotsamples/MainActivity.kt#L117
when [1] exists, the classloader will cause an exception. this line could be changed to something like: 
"val sampleClass = try { classLoader?.loadClass(name) } catch(e:Exception) { null }", and the end of next if {} block should have a return between line 120 and 121 here https://github.com/aws/aws-iot-device-sdk-java-v2/blob/main/samples/Android/app/src/main/java/software/amazon/awssdk/iotsamples/MainActivity.kt#L120

### Expected Behavior

[1] it runs respect samples. 
[2] it prints the error and return.

### Current Behavior

[1] it does not run the sample, instead it crashes.
[2] it does not print the error. if [1] is fixed, it would print the error, but it will continue to launch the thread with a null "sampleClass" that's unnecessary. 

### Reproduction Steps

just build tne android app and run it. select a sample from the drop-down selection.

### Possible Solution

see the description. specifically: 
[1] change 
```
        main {
            java.srcDir '../..Utils/CommandLineUtils'
            java.srcDir '../..BasicPubSub/src/main/java'
            java.srcDir '../..Jobs/src/main/java'
            java.srcDir '../..Shadow/src/main/java'
            java.srcDir '../..CognitoConnect/src/main/java'
            java.srcDir 'src/main/java'
        }
```
to
```
        main {
            java.srcDir '../../Utils/CommandLineUtils'
            java.srcDir '../../BasicPubSub/src/main/java'
            java.srcDir '../../Jobs/src/main/java'
            java.srcDir '../../Shadow/src/main/java'
            java.srcDir '../../CognitoConnect/src/main/java'
            java.srcDir 'src/main/java'
        }
```

[2] change 
```
        val classLoader = Thread.currentThread().contextClassLoader
        val sampleClass = classLoader?.loadClass(name);
        if (sampleClass == null) {
            clearConsole()
            writeToConsole("Could not find sample '${name}'")
        }
        writeToConsole("Running sample '${name}'\n")
```
to
```
        val classLoader = Thread.currentThread().contextClassLoader
        val sampleClass = try { classLoader?.loadClass(name) } catch(e:Exception) { null }
        if (sampleClass == null) {
            clearConsole()
            writeToConsole("Could not find sample '${name}'")
            return
        }
        writeToConsole("Running sample '${name}'\n")
```

### SDK version used

1.17.0

### Environment details (OS name and version, etc.)

android studio any version should behave the same

**Comment by jmklix** [comment]
Thanks for pointing this out. I'm working on creating the PR to fix both issues.
