### ISSUE TITLE
SDK lists Jackson as a dependency

### ISSUE THREAD

**Issue by MikeDombo** [aws/aws-iot-device-sdk-java-v2#497]
### Describe the bug

Jackson isn't used by the SDK from what I can tell and it is bringing an older version of jackson core.

### Expected Behavior

Don't need jackson

### Current Behavior

Depends on jackson

### Reproduction Steps

https://github.com/aws/aws-iot-device-sdk-java-v2/blame/b7c1a824a029600d3fc4de91db24a08ebdf04c16/sdk/pom.xml#L77-L79

### SDK version used

Latest

### Environment details (OS name and version, etc.)

none

**Comment by jmklix** [comment]
Created PR and I will merge when it passes the tests
