### ISSUE TITLE
Add documentation for Windows

### ISSUE THREAD

**Issue by massi-ang** [aws/aws-iot-device-sdk-java-v2#64]
**Is your feature request related to a problem? Please describe.**
Provide clearer instructions on how to build the dependencies (like the CRT) on Wondows

**Describe the solution you'd like**
Updated documentation

**Comment by justinboswell** [comment]
The dependencies should not need to be built on windows. We provide pre-built shared libraries. That said, the aws-crt-java README has recently been updated with additional build instructions.

What is the use-case where you're having to compile on windows?

**Comment by massi-ang** [comment]
For completeness it could be good to add this information in the README. 

* dependencies should not be needed on windows, as pre-built libraries are provided
* instruction to build the aws-crt-java library can be found ...

**Comment by jmklix** [comment]
Could you elaborate on why you think that should be added to the README? Did you have any difficulties installing the sdk?

**Comment by massi-ang** [comment]
As you have a generic section to build the crt from sources and one specific to Android, it could be good to have a specific section for windows, maybe pointing to the aws-crt-java docs (https://github.com/awslabs/aws-crt-java#windows)

**Comment by justinboswell** [comment]
We can add a link for sure, but we still want to understand why anyone would be compiling the CRT themselves, especially as a consumer of the IoT Device SDK. We do not intend for downstream users to have to do that except in the most esoteric of cases; we provide binaries via the package managers. Can you give some details on the use case for building as a consumer of the IoT Device SDK?
