### ISSUE TITLE
X509CredentialsProviderBuilder Does not use HttpProxyOptions when requesting credentials from the endpoint

### ISSUE THREAD

**Issue by AmeliaMcMullen** [aws/aws-iot-device-sdk-java-v2#66]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Known Issue**
- [X] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
A customer is trying to connect to websockets over proxy, but all traffic not through the proxy is blocked by a firewall. The MQTT requests after being connected go through the proxy, but not the credentials requests before hand, so the device can never be connected because the credentials provider is connecting directly.

**SDK version number**
SDK number: 0.5.6 

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Samsung galaxy S9 - Oreo

**To Reproduce (observed behavior)**
Run the credentials provider example and note that the request to get the credentials does not go through the proxy.

**Expected behavior**
The request to get the credentials goes through the proxy.

**Logs/output**
If applicable, add logs or error output.
No logs available. Monitor traffic on the proxy during test.

To enable logging, set the following system properties:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
-Daws.crt.debugnative=true
-Daws.crt.log.destination=File
-Daws.crt.log.level=Trace
-Daws.crt.log.filename=<path and filename>
```

**Additional context**

**Comment by bretambrose** [comment]
Proxy support for x509 was added in crt version 0.5.7:  https://github.com/awslabs/aws-crt-java/releases/tag/v0.5.7

Please reopen if the customer has problems/issues using it.
