### ISSUE TITLE
AWSIotMqttClient support for CredentialsProvider

### ISSUE THREAD

**Issue by mygordienko** [aws/aws-iot-device-sdk-java-v2#76]
In order to create instance of AWSIotMqttClient the one have to explicitly provide certificate
and private key (if certificate authentication is used for a device). The problem is that Mqtt cliet has
state (subscriptions), which is supposed to be kept between connections (client code does not care about
connection issues). But credentials may be subject to change, consider the following scenario:

Device uses two types of certificates: bootstrap and main. When connecting for the first time there is only
bootstrap certificate. After bootstrap procedure is done and device has got its main certificate, the bootstrap
certificate can be removed.

It would be nice to have AWSIotMqttClient instance created at device startup and injected it wherever needed.
The client code basicaly does not care about credentials type (bootstrap or main), it just need a client.
I could implement custom CredentialsProvider, which

* searches first for main certificate in dedicated location
* if failed, searches for bootstrap certificate in dedicated location
* throws an error

and this is transparent for the rest of the client.

Original issue for V1: https://github.com/aws/aws-iot-device-sdk-java/issues/143

**Comment by bretambrose** [comment]
Would the new identity client help with your use case (https://aws.amazon.com/about-aws/whats-new/2020/04/announcing-general-availability-of-aws-iot-core-fleet-provisioning/) ?  A one-time per-device cert provisioning feels very different operationally than a persistent IoT device application.  It may not be ideal, but splitting the two concerns into separate applications might be the way to go.

As for the feature request, I could be missing a simplification, but supporting a dynamic tls context at reconnect time would be a very large refactor across 3 or more libraries at a bare minimum.

**Comment by mygordienko** [comment]
Thanks for your reply!

As far as I can see, the new procedure is not different from what I use now with regards to certificate rotation.
Device still needs to switch to a new certificate. For example [here](https://github.com/aws-samples/aws-iot-fleet-provisioning/blob/master/provisioning_handler.py) 
two separate MQTTClient instances are created for bootstrap and main certificates.  My point is to create one instance and configure certificate resolution policy.

**Comment by bretambrose** [comment]
I see.

Well, it's an interesting use case, but given the substantial refactor it would involve across multiple libraries, I just don't think it's something we'll be able to support anytime soon.
