### ISSUE TITLE
AndroidKeyStore support

### ISSUE THREAD

**Issue by NiklasReisser** [aws/aws-iot-device-sdk-java-v2#84]
Hi, 

I would like to use this sdk for an Android-Device. 
Currently I am working on the fleet provisioning. For creating/storing the device' private key, I would like to use Android Keystore or KeyChain. (https://developer.android.com/training/articles/keystore) 
The SDK Api seems to expect direct access to the private key, either as bytearray or file. This is something Android's Keystore does not support. 

So my question is, can I use the Android KeyStore with this sdk, and if not, what is the recommended way to store the private key in a secure manner on an Android Device?

A technical detail for which I would greatly appreciate, but don't really expect, support:
Our current software is actually written in Python. We ported it to Android using python-for-android. (Including aws-iot-device-sdk-python-v2). Due to schedule constraints we would like to avoid re-writing everything in Java/Kotlin. 
Can you think of way to do the above in python? :) 

Thanks in advance and best regards, 

Niklas

**Comment by jmklix** [comment]
Hello NiklasReisser,
Sorry, but we do not support Android Keystore. You can store the private key in the user home directory, under .ssh/id_rsa. No matter where you put it the path should have least permissions (600) that only the intended user can read and no one else on the system can read.

**Comment by NiklasReisser** [comment]
Hi jmklix

Thats unfortunate. Thanks for the fast reply though. 

Regards
Niklas
