### ISSUE TITLE
Cannot connect to SOCKS proxy

### ISSUE THREAD

**Issue by AmeliaMcMullen** [aws/aws-iot-device-sdk-java-v2#86]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Known Issue**
- [X] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Describe the bug**
While using this new SDK I am able to connect to an HTTP proxy but when my proxy is SOCKS, it does not connect. I don't see a stack trace but it doesn't not connect and I don't see any communication through my proxy.
Is it expected that this SDK will support SOCKS proxy? Is there anything specific that has to be configured for SOCKS vs HTTP?

**SDK version number**
SDK: 1.2.4
CRT: 0.6.2

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Samsung Galaxy S9
Android 8.0.0
Charles Proxy (free)

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
Attempt to run a sample application and connect to a SOCKS proxy.

**Expected behavior**
Connect to the SOCKS proxy.

**Logs/output**
If applicable, add logs or error output.
No logs available.

**Comment by bretambrose** [comment]
We do not have SOCKS support implemented yet.  What kind of auth support would be sufficient for your use case?  Basic (and no authentication at all) would be reasonably straightforward to implement, but GSSAPI would probably be a lot more work.

**Comment by AmeliaMcMullen** [comment]
We don't have any authentication for the proxy.

**Comment by vudh1** [comment]
testing sentiment: This is Terrible

**Comment by vudh1** [comment]
this is so terrible experience. worst experience ever

**Comment by vudhone** [comment]
this is terrible experience, worst experience I ever had - Daniel (testing)

**Comment by pbryniarski-logi** [comment]
Hi,
I'd like to ask what is the status of this issue?
Some of our customers are using SOCKS proxy (we are currently using sdk v1), we need to start supporting both HTTP and SOCKS proxy in our products but v2 SDK lacks SOCKS proxy.
Could you please prioritize this issue and ensure API parity so we can migrate from v1 to v2 SDK?
Thank you.

**Comment by bretambrose** [comment]
Socks support isn't on any roadmap or planning atm.

What kind of authentication support would you need?

**Comment by pbryniarski-logi** [comment]
I don't think we need any auth at the moment. v1 sdk does not support proxy authentication as well

https://github.com/aws-amplify/aws-sdk-android/blob/8de48797ae2e5c157169a94746c768da7de61056/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L841

SOCKS5 is ok.

**Comment by bretambrose** [comment]
Understood.

One final thing, not trying to be pedantic, but clarity is important for setting expectations for feature parity and all: amplify's android sdk is a separate product that has no relation (externally or corporate-internal) with the IoT SDKs ; the v1 IoT SDK is [here](https://github.com/aws/aws-iot-device-sdk-java)

**Comment by pbryniarski-logi** [comment]
> One final thing, not trying to be pedantic, but clarity is important for setting expectations for feature parity and all: amplify's android sdk is a separate product that has no relation (externally or corporate-internal) with the IoT SDKs ; the v1 IoT SDK is [here](https://github.com/aws/aws-iot-device-sdk-java)

Thank you for the clarification, tbh I'm bit confused on all those different SDK's and its versions.

**Comment by jmklix** [comment]
Closing this as not planned due to resource constraints. If you still would like to use this sdk with SOCKS proxy please open a new feature request.
