### ISSUE TITLE
Unable to resolve Dependency

### ISSUE THREAD

**Issue by rajkumu12** [aws/aws-iot-device-sdk-java-v2#87]
I have imported android project into my android studio synced it is giving following issue what should i do

Failed to resolve: software.amazon.awssdk.crt:android:0.6.2
Show in Project Structure dialog
Affected Modules: app

i tried every possible thing it didn't work

**Comment by bretambrose** [comment]
The gradle build crt dependency has a tendency to get missed since I always forget about it.  You can try manually bumping all 0.6.2s to 0.6.5s locally for now, but either way I'll update it later today.

**Comment by bretambrose** [comment]
The android build is still a work-in-progress and requires some extra steps from you until it gets finished off:

1. We don't publish android packages to maven yet.  You will need to build and install the aws CRT dependency yourself.
1. Start by pulling the matching release from https://github.com/awslabs/aws-crt-java/
1. ./gradle build
1. ./gradle publishToMavenLocal
1. You may need to locally modify the requested NDK version to match what you have installed
1. Now build the v2 sdk, again you may need to locally modify the NDK version in the build settings

**Comment by AagamMehta** [comment]
Thanks for your support
I have followed all said steps including configuring ndk but still getting issue while setup this project

Failed to resolve: software.amazon.awssdk.crt:android:0.6.5
Show in Project Structure dialog
Affected Modules: app

Overall issue is I am not able to run this project
So that i can't see any log.

(Getting same error as @rajkumu12 when following the steps guided by @bretambrose. The same comment posted on Issue #85 )

**Comment by bretambrose** [comment]
My instructions could have been clearer: "pulling the matching release" should have been more explicit.  You need to checkout the v0.6.5 release of the crt before building:
```
git checkout v0.6.5
```

You'll also need to get submodules in sync after doing so.

So better instructions, from scratch:
```
git clone git@github.com:awslabs/aws-crt-java
cd aws-crt-java
git checkout v0.6.5
git submodule update --init
cd android
./gradlew build
./gradlew publishToMavenLocal
```

**Comment by rajkumu12** [comment]
I am still having same issue  as I have mentioned before that without resolving dependency I can't move ahead so my issue is still remain same 
Failed to resolve: software.amazon.awssdk.crt:android:0.6.5
Show in Project Structure dialog
Affected Modules: app

**Comment by bretambrose** [comment]
I assume all the steps were successful?

What output do you get when you recursively display all the contents in the local maven repository under software/amazon/awssdk/crt?  ie

```
ls -R .m2/repository/software/amazon/awssdk/crt
```

**Comment by rajkumu12** [comment]
i have resolved dependency issue successfully but i want to run app on android device 
and i am unable generate app build to run on android and which section will work for android i have imported whole project i want on android section or i want to use this dependency directly in my existing project how can i achieve this.

**Comment by bretambrose** [comment]
As mentioned before, our Android support is still a work in progress and won't be ideal until we're properly publishing android jars to maven central.  In the meantime, I don't really have the expertise to advise on android project management details using locally built jars.
