### ISSUE TITLE
Can we use java-v2 maven release for Android?

### ISSUE THREAD

**Issue by codegame6** [aws/aws-iot-device-sdk-java-v2#89]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Android

**Describe the question**
I am using java-v2 SDK for Android. I am aware that it is possible to build SDK for Android but it is much easier to use maven repository build especially when need to update to the latest version for required fixes. I have already tried to use package 'software.amazon.awssdk.iotdevicesdk:aws-iot-device-sdk:1.2.6' but it is not working for Android due to the below error.
Unable to open library in jar for AWS CRT: /android/arm64-v8a/libaws-crt-jni.so

I have read below issues but it is not clear if it is possible and if it is then which aws-crt package is required.
https://github.com/aws/aws-iot-device-sdk-java-v2/issues/69
https://github.com/aws/aws-iot-device-sdk-java-v2/issues/87

**Comment by bretambrose** [comment]
Publishing android builds to maven central is something that is scheduled to get worked on in the next month or so.  Until then, you'll need to build manually.

**Comment by codegame6** [comment]
Thank you.

**Comment by codegame6** [comment]
It is now more than 2 months. Is there any plan to publish android builds?

**Comment by bretambrose** [comment]
We've had some priority shifts recently.  That work is still in progress but I don't have an ETA for its completion.

**Comment by codegame6** [comment]
Is it something which can be done before end of this year?

**Comment by shawzyen** [comment]
Expect this feature to be completed soon.

**Comment by bretambrose** [comment]
We're not really able to comment on timelines for things not under direct development/prioritization.  If you have an AWS TAM that you work with, you can engage with them and we can prioritize/talk further through that channel.

**Comment by jmklix** [comment]
Closing this feature request because currently [AWS Amplify](https://aws.amazon.com/amplify/) is the current tool recommended to develop for android devices. This is not saying that this sdk will never be supported on android, but it is not planned in the near future.

**Comment by uberbinge** [comment]
Can we please open this again? As now we have CRT android published on maven central, it would really help if this is also available there. Thanks!
