### ISSUE TITLE
[URGENT] Unable to connect to ATS endpoint

### ISSUE THREAD

**Issue by AmeliaMcMullen** [aws/aws-iot-device-sdk-java-v2#91]
Confirm by changing [ ] to [x] below:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Samsung Galaxy S8
Android 8

**Describe the question**

I am currently using this SDK to connect through a proxy and it worked on 2 out of 3 of our AWS accounts. The two accounts it worked on are more lenient with permissions than the third that is not currently working. During connection it is successfully able to go through the proxy, hit the credentials provider and get a response back. It does NOT hit the proxy when attempting to connect to the ATS endpoint and eventually our app says "Application is not responding".
These are the logs I see:
```
V/AuthCredentialsProvider: [00000074ee35b4f0]  - (id=0x7502a20080) X509 credentials provider received 27 response bytes
D/http-stream: [00000074ee35b4f0]  - id=0x74ed351600: Client request complete, response status: 403 (Forbidden).
V/http-stream: [00000074ee35b4f0]  - id=0x74ed351600: Stream refcount released, 1 remaining.
E/AuthCredentialsProvider: [00000074ee35b4f0]  - Failed to parse IoT Core response as Json document.
W/AuthCredentialsProvider: [00000074ee35b4f0]  - (id=0x7502a20080) X509 credentials provider failed to query credentials with error 6156(Unsuccessful status code returned from credentials-fetching http request)
E/AuthSigning: [00000074ee35b4f0]  - (id=0x7502a17580) Credentials Provider failed to source credentials with error 6156(aws-c-auth: AWS_AUTH_CREDENTIALS_PROVIDER_HTTP_STATUS_FAILURE, Unsuccessful status code returned from credentials-fetching http request)
```
Between the working aws account and the not working account, I have verified our existing policy has "iot:AssumeRoleWithCertificate" added to it, that the IAM policy role alias is as expected, and verified the IAM policies match. 

**Is there a permission that could be missing in order to use this SDK to connect to aws/proxy? Is there anywhere you can tell us to check from one account to another and make sure they match?**

**Comment by bretambrose** [comment]
From a priority/urgency standpoint, if you haven't already done so, reach out to your AWS SA and have them escalate this to IoT Core.  X509 provider permissions policy problems will be most easily resolved through them.  Give them each account's policy.

**Comment by AmeliaMcMullen** [comment]
This issue turned out to be a configuration issue in the account. Thank you for your help.

**Comment by ylu999** [comment]
Faced the same issue.
I'm using x509 with roleAlias.  

So basically form iot policy, I just need to setup "Action":"iot:AssumeRoleWithCertificate" since it's assuming as IAM role.

Then from iam policy, set all iot policy needed like Connect, Publish, UpdateThingShadow, etc.

**Comment by andrescencerrado** [comment]
Make sure your role alias' credential duration is shorter than (or same as) the maximum session duration of the IAM role it's aliasing.
