### ISSUE TITLE
Is it possible to know reason for connection error?

### ISSUE THREAD

**Issue by codegame6** [aws/aws-iot-device-sdk-java-v2#99]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-java-v2/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
Android

**Describe the question**
I am using java-v2 SDK for Android. To establish an MQTT connection I am using the connect API of MqttClientConnection. When the connection fails, it provides ExecutionException but is there any way by which we can know the error number or some other detail by which we can know the cause of connection error like not able to connect to the server, certificate error or any other error. So, it can be used to take appropriate action like try to recover error if possible or show user appropriate error on UI.

**Comment by bretambrose** [comment]
We don't throw ExecutionExceptions directly, so if you see it is almost certainly a wrapper around an exception that was applied to the future representing an async operation (https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutionException.html)  What do you get if you call getCause() on the ExecutionException?
